### ISSUE TITLE
stalling connection leads to indefinite waiting

### ISSUE THREAD

**Issue by ordex** [axel-download-accelerator/axel#101]
When one of the connections stalls for any reason, Axel will take an enormous amount of time before timing it out and trying again. I usually kill axel and start it again to make the procedure faster.

I think we should tweak the TCP/connection timeout so that axel can be more reactive.

**Comment by ismaell** [comment]
* send/recv: use `setsockopts` with `SO_SNDTIMEO` and `SO_RCVTIMEO` respectively.
* connection: set `O_NONBLOCK` and `select` with a single fd and a timeout, then clear `O_NONBLOCK`.

**Comment by ismaell** [comment]
@ordex do you want to tackle this one?

**Comment by ordex** [comment]
Yes, I can have a look

**Comment by ismaell** [comment]
@ordex what would be a reasonable timeout value?

**Comment by ordex** [comment]
@ismaell I don't have a value in mind. But maybe we could check what wget does in these cases?

**Comment by ismaell** [comment]
@ordex 900 seconds for wget, seems a little bit too high, perhaps we should use 2 minutes...

**Comment by ordex** [comment]
yeah I agree. I don't think 900 seconds can be useful at all.
