### ISSUE TITLE
Downloads stall when about to reach 100%

### ISSUE THREAD

**Issue by ismaell** [axel-download-accelerator/axel#106]
Likely something is wrong with the speed check in `axel_do` (shown in the backtrace), the last thread gets stuck in a loop calling `axel_nanosleep`.

**Comment by ismaell** [comment]
Fixed by commit e6422f833bb4925bc6b37e429640e620a124ecb1.

**Comment by davoudarsalani** [comment]
Hi. I've installed axel via pacman. Is there a way I can fix this?

**Comment by ismaell** [comment]
> Hi. I've installed axel via pacman. Is there a way I can fix this?

This issue was fixed in v2.14.1...

Which distribution is it?

**Comment by davoudarsalani** [comment]
It's on Arch.
What I have tried so far is that I removed the one I had installed via pacman (axel 2.17.7-1) and installed it using github source. But I still have the same problem.

**Comment by ismaell** [comment]
> It's on Arch.
> What I have tried so far is that I removed the one I had installed via pacman (axel 2.17.7-1) and installed it using github source. But I still have the same problem.

Then you have another (unrelated but similar) problem. Can you provide a trace?

**Comment by davoudarsalani** [comment]
By "trace" do you mean the download output?
Actually I haven't had the problem as much since I have installed it from source but it does happen from time to time. I'll post the output the next time I experience it again.

**Comment by NickSun** [comment]
Is it possible to add --min-speed option? Downloads stall sometimes when about to reach 100%.
Axel version 2.16.1 (Linux)

**Comment by ismaell** [comment]
@davoudarsalani I meant syscall trace like the one generated by `strace`.

@NickSun some form of stall detection would not be a bad idea, indeed. Mind opening a feature request?

**Comment by NickSun** [comment]
> @NickSun some form of stall detection would not be a bad idea, indeed. Mind opening a feature request?

done #260
