### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by ordex** [axel-download-accelerator/axel#113]
We are currently working on an Italian translation to be integrated with the rest.
Lang code will be: `it_IT`

**Comment by eribertomota** [comment]
Em quarta-feira, 20 de setembro de 2017, Antonio Quartulli <
notifications@github.com> escreveu:

> We are currently working on an Italian translation to be integrated with
> the rest.
> Lang code will be: it_IT
>
>
Very good!

**Comment by ordex** [comment]
@eribertomota I have copied the it_IT.po file in the po directory and added it to the LINGUAS file.
Then I have cleaned up my repo and restarted with autogen.sh... I see the it_IT.po file being used during the processing, but then, when I run Axel it still prints messages in English. What do I need to change to run it in Italian?
I have executed:
`export LINGUAS=it_IT`

**Comment by eribertomota** [comment]
2017-09-21 1:03 GMT-03:00 Antonio Quartulli <notifications@github.com>:

> @eribertomota <https://github.com/eribertomota> I have copied the
> it_IT.po file in the po directory and added it to the LINGUAS file.
> Then I have cleaned up my repo and restarted with autogen.sh... I see the
> it_IT.po file being used during the processing, but then, when I run Axel
> it still prints messages in English. What do I need to change to run it in
> Italian?
> I have executed:
> export LINGUAS=it_IT
>


Hi,

You need to run 'make update-po' inside po/ directory.

**Comment by ismaell** [comment]
It should be something like: `export LANG=it_IT.UTF-8`

**Comment by ordex** [comment]
I think the UTF-8 part is for LANG/LC_ALL, but not for LINGUAS.

By the way, something is wrong with what I am doing in axel, because after exporting the LINGUAS=it_IT, other command line tools are converting to Italian, while axel is still in english.

I ran make update-po

**Comment by ordex** [comment]
I'll upload the changes so you all can have a look

**Comment by ismaell** [comment]
@ordex Ah, wait, you meant to _generate_ only `it_IT`... ok, that's probably working, is the `.mo` file installed?

**Comment by ordex** [comment]
@ismaell the .mo file is created, but must I *install* the .mo files somewhere in the system? or is it supposed to work even when running from the build folder?

**Comment by eribertomota** [comment]
2017-09-22 2:00 GMT-03:00 Antonio Quartulli <notifications@github.com>:

> @ismaell <https://github.com/ismaell> the .mo file is created, but must I
> *install* the .mo files somewhere in the system? or is it supposed to
> work even when running from the build folder?
>


See here the final files in to be distributed by Debian package:
https://packages.debian.org/sid/amd64/axel/filelist

**Comment by ordex** [comment]
I see. Very useful, thanks!

**Comment by ordex** [comment]
Ok, I made it work! The location where the .mo file are looked up can be changed with --localedir passed to ./configure (if this can be helpful).
