### ISSUE TITLE
Flashgot+axel not working properly

### ISSUE THREAD

**Issue by eribertomota** [axel-download-accelerator/axel#117]
From Ubuntu[1]:

downloaded using flashgot+aria2 got proper downloads

but tried it using axel+flashgot all i got was image which could not be read.

type of download - all jpg images
60% of them 453 bytes and remaining 456 bytes

at the same time aria went through and got all properly ranging from 41 to 188 kb

for axel some of the errors that i got were
too many redirects.
server unsupported.
starting from scratch 1 connection

flashgot

aria2 - ok
axel - ok
wget-ok

ko for everything else

[1] https://bugs.launchpad.net/ubuntu/+source/axel/+bug/899867

Regards,

Eriberto

**Comment by ismaell** [comment]
@eribertomota @ordex  do you guys know if this still is broken?

**Comment by eribertomota** [comment]
Flashgot is deprecated and no longer supported by Firefox. Axel is updated and working fine. So, I closing this bug. Feel free to reopen.
