### ISSUE TITLE
Sites that block Axel

### ISSUE THREAD

**Issue by ismaell** [axel-download-accelerator/axel#119]
- [x] http://alioth.debian.org/ complains with error 406.

**Comment by ordex** [comment]
@ismaell can you explain better what you mean with "block"? You mean that prevent axel from doing multiple connections?

**Comment by ismaell** [comment]
@ordex sites that block/filter by User-Agent, returning some error code instead of the file.

**Comment by ismaell** [comment]
@ordex was a false positive anyway :/.

**Comment by ismaell** [comment]
Fixed.
