### ISSUE TITLE
axel 2.15 and --quiet

### ISSUE THREAD

**Issue by zaza42** [axel-download-accelerator/axel#133]
axel 2.15 produces 0 bytes long output when using `--quiet` option.

```
$ axel http://tgftp.nws.noaa.gov/data/observations/metar/decoded/LHBP.TXT
Initializing download: http://tgftp.nws.noaa.gov/data/observations/metar/decoded/LHBP.TXT
File size: 322 bytes
Opening output file LHBP.TXT
Starting download

Connection 0 finished

Downloaded 322 byte in 0 seconds. (0.78 KB/s)
$ ls -la LHBP.TXT
-rw-r--r--  1 user user 322 Oct 19 17:15 LHBP.TXT
$ rm LHBP.TXT
$ axel http://tgftp.nws.noaa.gov/data/observations/metar/decoded/LHBP.TXT --quiet
$ ls -la LHBP.TXT
-rw-r--r--  1 user user   0 Oct 19 17:15 LHBP.TXT
```
Version 2.14 works well without this bug.

**Comment by ordex** [comment]
Hi @zaza42 , thanks a lot for your bug report! I just tried myself and I could easily reproduce the issue.
I will try to see where the bug is coming from. Thanks for testing 2.14 too!

**Comment by ordex** [comment]
Apparently I introduced the bug with 452e51ea223132c52694e40a8e27108e1600f90c
There must be something weird going on .. because the --quiet argument should have no effect on that code.

**Comment by ismaell** [comment]
I'm seeing the source of the bug.

**Comment by ordex** [comment]
super! @zaza42 if you want, you could test the master branch to ensure the issue is gone for you

**Comment by zaza42** [comment]
Ok, the bug has gone away. Thanx for instant patching!
