### ISSUE TITLE
FTBFS in 2.16.1 version

### ISSUE THREAD

**Issue by eribertomota** [axel-download-accelerator/axel#137]
Hi,

On Debian, the version 2.16.1 fails to build from source:

```
./configure: line 2928: PKG_PROG_PKG_CONFIG: command not found
[...]
./configure: line 4845: syntax error near unexpected token `SSL,'
./configure: line 4845: `    PKG_CHECK_MODULES(SSL, openssl)'
```

I attached a full log.

Cheers,

Eriberto

[axel_2.16.1-1_amd64.build.zip](https://github.com/axel-download-accelerator/axel/files/1531021/axel_2.16.1-1_amd64.build.zip)

**Comment by ismaell** [comment]
Switch to the release tarballs. I already made a case against using the repo directly in a private email thread...

Even if you fix the dependency, keep in mind what I previously said: if build environments were to differ, even minimally, it could produce a non-reproducible build. This is an issue for any non-self-contained buildsystem.

**Comment by eribertomota** [comment]
Debian always use a clean jail (created for each build). Now, Axel uses pkg-config and it was not in build dependencies inside Debian package. It was producing the error message "PKG_PROG_PKG_CONFIG: command not found". Can you add a friendly message in check for 'pkg-config' presence in configure.ac to help the users?

After some tests, I think that release tarball is not proper for Debian. There are several differences between the files provided by GitHub and the release tarballs. Inside release tarballs, no longer exist the 'autogen.sh' file, described by README file. Going back to Debian, when building, the debhelp always will run 'make distclean, autoreconf -fi, ./configure, make'. So, all prebuilt files, as configure, Makefile.in, po/*gmo, will be dropped. It works fine for all upstreams and the v2.16.1.tar.gz is building ok now.

**Comment by eribertomota** [comment]
I just uploaded axel to Debian. Thanks.

**Comment by ismaell** [comment]
Repeat-ability aside, running `autoreconf` shouldn't fail from the release tarball because the required `m4` files are bundled by Automake's `dist` target automatically.

**Comment by eribertomota** [comment]
I just uploaded axel to Debian. Thanks.

**Comment by eribertomota** [comment]
What you think about to add a message inside README to warning that pkg-config is a build dependency?

**Comment by ismaell** [comment]
Done.
