### ISSUE TITLE
Building v2.6 on Ubuntu 16.04

### ISSUE THREAD

**Issue by junaid-ali** [axel-download-accelerator/axel#141]
The latest axel version available on Xenial is v2.5-2
```
$ apt-cache policy axel
axel:
  Installed: 2.5-2
  Candidate: 2.5-2
  Version table:
 *** 2.5-2 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
```
This version doesn't support SSL/TLS.

While building v2.6 from source code, there was an issue with aclocal command:
`aclocal-1.14: command not found`

In 16.04, aclocal's installed version is 1.15
```
$ aclocal --version
aclocal (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.
```

To **workaround** this issue, I had to update `line#2261` in `configure` file so that `am__api_version` points to `1.15` instead to `1.14`

**Comment by ordex** [comment]
that is extremely old.
The latest version available is 2.16.1. Have you tried compiling that one from source?

**Comment by junaid-ali** [comment]
I tried with master but there were errors. I will look into building with 2.16.

**Comment by ismaell** [comment]
@junaid-ali please try 2.16.1 and file a new bug report if you find any problems.
