### ISSUE TITLE
default download path

### ISSUE THREAD

**Issue by imeilige** [axel-download-accelerator/axel#143]
How to set the default download path, such as / Users / xxx / Downloads

**Comment by ordex** [comment]
Hi, I am sorry but axel does not support "default download paths". It just downloads to the current directory or to a specific file that you indicate with the related option.

**Comment by ismaell** [comment]
@imeilige you just need to change to the desired directory first, maybe running it in a sub-shell, like this:

    (cd /Users/xxx/Downloads && exec axel ...)
