### ISSUE TITLE
No 'configure' in cloned repo

### ISSUE THREAD

**Issue by RedactedCode** [axel-download-accelerator/axel#145]
I'm used to getting source from github & compiling it for my distro (Puppy Linux)

I've just done 'git clone https://github.com/axel-download-accelerator/axel.git' but
'configure' is not included in the cloned repo and it isn't in the zip file if I download that.

The INSTALL doc explicitly states that './configure' should be run (like with almost any other package) before 'make'.

**Comment by ordex** [comment]
As reported in the README

> Release tarballs contain a pre-generated buildsystem, but if you need to edit/patch it, or you're building from a copy of the repository, then you may need to run autoreconf -i to generate it
