### ISSUE TITLE
Support Android which lacks pthread_cancel()

### ISSUE THREAD

**Issue by fornwall** [axel-download-accelerator/axel#150]
The Android libc lacks `pthread_cancel()`.

[Termux](https://termux.com) does now have an axel package contributed by @Hax4us in https://github.com/termux/termux-packages/pull/2248, which simply replaces `pthread_cancel` with `pthread_kill`.

I don't know anything about axel, so I wonder:

(1) Does the patch used in the Termux package make sense?
(2) Could support for building axel on Android (by replacing `pthread_cancel` useage) be possible in this project?

**Comment by ordex** [comment]
hi @fornwall and thanks for opening this ticket. It makes sense to support Android directly in our codebase, especially since the required change is so small.

Maybe we could ask @Hax4us to send a patch to us directly?

@ismaell what do you think about using `pthread_kill` instead of `pthread_cancel` only for android? It should be reasonable, no?

**Comment by ismaell** [comment]
@fornwall @ordex The proper way to make it build would be to provide implementations for the missing functions, which would do the same without requiring edits to the code nor `#ifdefs`, then conditionally include a header file containing those wherever there's a `#include <pthread.h>`.

**Comment by ordex** [comment]
that would be the ideal fix upstream and normally Android takes care of that in its NDK, but apparently there is nothing for this function.

**Comment by ismaell** [comment]
Something like the following in the header file, let's call it `"android-compat.h"`:

    int pthread_cancel(pthread_t h) {
            return pthread_kill(h, 0);
    }
   ...

Then run:

    sed -i '/^#include <pthread[.]h>/a#include "android-compat.h"' src/axel.h

**Comment by ordex** [comment]
that would remove all the pthread.h inclusions, no? but we need to do that only when compiling for Android

**Comment by ismaell** [comment]
I'll create a branch for it, and let's wait some feedback.

**Comment by ismaell** [comment]
It's in branch `android-compat` now: https://github.com/axel-download-accelerator/axel/commit/411629ff2a7c8b1d896c62d0c09cd5b8e2e1ff67

We could do it better and add a signal handler to emulate an async pthread_cancel...

**Comment by Hax4us** [comment]
Can we do something like this 
`
if ( (status = pthread_kill(pthread_id, SIGUSR1)) != 0) 
{ 
printf("Error cancelling thread %d, error = %d (%s)", pthread_id, status, strerror status));
} 

USR1 handler:

struct sigaction actions;
memset(&actions, 0, sizeof(actions)); 
sigemptyset(&actions.sa_mask);
actions.sa_flags = 0; 
actions.sa_handler = thread_exit_handler;
rc = sigaction(SIGUSR1,&actions,NULL);
void thread_exit_handler(int sig)
{ 
pthread_exit(0);
}`

**Comment by ismaell** [comment]
@Hax4us indeed.

Would you mind to make a patch?

**Comment by Hax4us** [comment]
I hope it will help you 
1) **workaround**
https://github.com/Hax4us/Hax4us.github.io/blob/master/Pthread_patches/apthread.h
2) **workaround**
https://github.com/Hax4us/Hax4us.github.io/blob/master/Pthread_patches/Bpthread.h

3) I have one more workaround basically it will not add any new header file. I will just add handler in Axel.c same as 2 workaround and this :

`if defined(__ANDROID__)
	pthread_sigmask(SIG_UNBLOCK, &setusr1, NULL);
#else
 pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, NULL);
#endif`

you can't expect more than this from me LOL , after all I am not professional as like you guys

**Comment by ismaell** [comment]
@Hax4us I like patch B, please submit a pull request with it.

**Comment by ismaell** [comment]
Support merged for v2.17.4.
