### ISSUE TITLE
Can not download large files

### ISSUE THREAD

**Issue by weiwangthu** [axel-download-accelerator/axel#151]
When I use axel to download  a large file with 12GB, it only downloads 2GB.

**Comment by ismaell** [comment]
Hi @weiwangthu,

How does it exactly fail?

**Comment by romanos** [comment]
@ismaell I'm having the same problem. It doesn't fail, it just only pulls the first 2GB of any large file. Shows all progress indicators based on 2GB file size and completes "successfully" after downloading 2GB. Some kind of 32-bit limit somewhere? I'm not sure. I've tried with multiple files, each of them over 100GB, so perhaps it's causing a problem somewhere.

**Comment by tkasarla** [comment]
@romanos even after building from source, it still fails for 5gb file I'm trying to download. It only downloaded 1.7gb and completed "successfully".

Do you have any idea how to fix this?

**Comment by romanos** [comment]
It fixed for me after installing latest version from source. I don't know what version that was offhand. (On mobile)

**Comment by tkasarla** [comment]
@romanos installed latest version now. It works! Thank you.
