### ISSUE TITLE
Improve error message on unsupported URL scheme

### ISSUE THREAD

**Issue by sarim** [axel-download-accelerator/axel#157]
shouldn't it fail and output an error?

**Comment by ismaell** [comment]
Yes, probably...

Patches are welcome.

**Comment by shankar** [comment]
It works as intended for me and i have configured and compiled axel from git head with `--without-ssl` option.
```
$ axel https://www.archlinux.org/releng/releases/2018.04.01/torrent/
Initializing download: https://www.archlinux.org/releng/releases/2018.04.01/torrent/
Could not parse URL.
```
It throws `Could not parse URL` error cuz the block parsing https and ftps protocols [here](https://github.com/axel-download-accelerator/axel/blob/1d555e7054e70ad5a8ab8457073982f02807127c/src/conn.c#L73) is not compiled.

**Comment by ismaell** [comment]
@shankar it's probably an older version. The error message could be improved though.

**Comment by sarim** [comment]
Sorry for late response. I installed axel from apt-get from ubuntu 14.04 repo and that version was silently converting https to http. I later cloned the master branch and didn't have any problem with that version.

**Comment by ismaell** [comment]
@sarim you need to open a bug against the distribution,so that they patch or upgrade the package. We can't do much from this project other than recommend you to compile it from sources.
