### ISSUE TITLE
Parse ftps/https schemes even without SSL support

### ISSUE THREAD

**Issue by ismaell** [axel-download-accelerator/axel#167]
https://github.com/axel-download-accelerator/axel/blob/73bf7ab3d7a560b728420092a7a6aabaeea986c1/src/conn.c#L73

**Comment by shankar** [comment]
I was thinking that there could be something like a "insecure mode" when ssl support is absent, where parsing of ftps/https schemes and downloading from the url works without checking for certificates.
like `--no-check-certificate` option in wget.

**Comment by ismaell** [comment]
We should just output an error, perhaps a suggestion about using `--insecure`, and fail, and if `--insecure` is used, fall back to http/ftp.

**Comment by ismaell** [comment]
Fixed by commit 4ee51f5c62f531e44ec15981edfaaa0336d6df87.
