### ISSUE TITLE
How can I give a files of urls to axel

### ISSUE THREAD

**Issue by riwogo** [axel-download-accelerator/axel#168]
I have a file like:

> url1
 url2
url3
.
.
.

and I want to give it to axel to download them in a queue how can I do that?

**Comment by aleao-sl** [comment]
How about
cat file.urllist.txt | xargs axel -n 15 -q

**Comment by pankajanand18** [comment]
the above mention solution provided by @aleao-sl looks good to me. Probably we should close this bug.
