### ISSUE TITLE
Version 2.16.1 src/text.c in print_alternate_output(axel_t *axel)

### ISSUE THREAD

**Issue by zusrt** [axel-download-accelerator/axel#172]
//width 40 to 41  30 to 31 for cursor
static void
print_alternate_output(axel_t *axel)
{
	long long int done = axel->bytes_done;
	long long int total = axel->size;
	double now = gettime();
	int width = get_term_width();
	char *progress;

	if (width < 41) { //40 to 41
		fprintf(stderr,
			_("Can't setup alternate output. Deactivating.\n"));
		axel->conf->alternate_output = 0;

		return;
	}

	width -= 31; //30 to 31

**Comment by ismaell** [comment]
Needs explanation.
