### ISSUE TITLE
subprocess

### ISSUE THREAD

**Issue by krypticallusion** [axel-download-accelerator/axel#179]
Hey!

I'm been using axel on terminal for a very long time and it worked as expected.

But someone while I was doing by python script and used subprocess to trigger axel, the download speed became very slow.

Code :

`args =  [axel, url]
cmd = subprocess.Popen(args, stdout=subprocess.PIPE)`

**Comment by krypticallusion** [comment]
Speed decrease was almost 10x lower than actual Speed given through terminal.

**Comment by ismaell** [comment]
Nothing to do with axel, you're not reading fast enough from the pipe.

**Comment by ismaell** [comment]
You can increase the buffer size if you can't read faster.
