### ISSUE TITLE
README says use "./configure" but no ./configure after cloning 

### ISSUE THREAD

**Issue by RedactedCode** [axel-download-accelerator/axel#180]
After git clone https://github.com/axel-download-accelerator/axel.git , the source appears to be lacking one vital thing for compilation: configure (there is a configure.ac) 

The readme says build with ./configure && make && make install like every other readme.

So README needs updating to say that ./autogen.sh needs to be run first to create ./configure

directory listing looks like this:
-rwxrwxrwx 1 root root  94K Oct 17 22:57 ABOUT-NLS
-rwxrwxrwx 1 root root  334 Oct 17 22:57 AUTHORS
-rwxrwxrwx 1 root root 1.6K Oct 17 22:57 CONTRIBUTING.md
-rwxrwxrwx 1 root root  18K Oct 17 22:57 COPYING
-rwxrwxrwx 1 root root 5.5K Oct 17 22:57 CREDITS
-rwxrwxrwx 1 root root  22K Oct 17 22:57 ChangeLog
-rwxrwxrwx 1 root root  16K Oct 17 22:57 INSTALL
-rwxrwxrwx 1 root root 1.5K Oct 17 22:57 Makefile.am
-rwxrwxrwx 1 root root   64 Oct 17 22:57 NEWS
lrwxrwxrwx 1 root root   26 Oct 17 22:57 README -> README.md
-rwxrwxrwx 1 root root 3.5K Oct 17 22:57 README.md
-rwxrwxrwx 1 root root   28 Oct 17 22:57 VERSION
-rwxrwxrwx 1 root root 1.9K Oct 17 22:57 acinclude.m4
-rwxrwxrwx 1 root root 2.4K Oct 17 22:57 autogen.sh
-rwxrwxrwx 1 root root 2.7K Oct 17 22:57 configure.ac
drwxrwxrwx 1 root root    0 Oct 17 22:57 doc
drwxrwxrwx 1 root root    0 Oct 17 22:57 man
drwxrwxrwx 1 root root  472 Oct 17 22:57 po
drwxrwxrwx 1 root root  360 Oct 17 22:57 scripts
drwxrwxrwx 1 root root  536 Oct 17 22:57 src

**Comment by ismaell** [comment]
Use the release tarballs; you're not supposed to use the repo directly unless doing development.
