### ISSUE TITLE
axel 2.15 and --quiet: redux

### ISSUE THREAD

**Issue by umayrh** [axel-download-accelerator/axel#192]
The issue previously described in #133 seems to have returned:

```
$ axel --quiet http://www-us.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz
$ ls -alh spark-2.4.0-bin-hadoop2.7.tgz
    -rw-r--r--  1 ***  ***     0B Jan 28 00:24 spark-2.4.0-bin-hadoop2.7.tgz
```

Using Axel version 2.15 (Darwin) but can also reproduce on a Trusty Travis container.

Happy to provide more information.

**Comment by ismaell** [comment]
Invalid report.

Upgrade Axel or at least apply [the fix](https://github.com/axel-download-accelerator/axel/commit/241c0c753b01f4ea1309195fec823382c6824a6d.patch).
