### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by sdfww** [axel-download-accelerator/axel#195]
I encountered an "undefined reference" error when compiling with Cygwin. It covers all versions after 2.5.
Only gettext v0.19 or higher is available in Cygwin.
Is this the problem and is there a solution?

$ make
make  all-recursive
make[1]: Entering directory `/home/1/axel'
Making all in src
make[2]:  `/home/1/axel/src'
  CC       axel.o
  CC       conf.o
  CC       conn.o
  CC       ftp.o
  CC       http.o
  CC       search.o
  CC       ssl.o
  CC       tcp.o
  CC       text.o
  CCLD     axel.exe
axel.o：In function `axel_open':
/home/1/axel/src/axel.c:224: undefined reference to `libintl_gettext'
/home/1/axel/src/axel.c:224:(.text+0x40b): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
/home/1/axel/src/axel.c:232: undefined reference to `libintl_gettext'
/home/1/axel/src/axel.c:232:(.text+0x456): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
/home/1/axel/src/axel.c:331: undefined reference to `libintl_gettext'
/home/1/axel/src/axel.c:331:(.text+0x6a4): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
/home/1/axel/src/axel.c:249: undefined reference to `libintl_gettext'
/home/1/axel/src/axel.c:249:(.text+0x758): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
/home/1/axel/src/axel.c:301: undefined reference to `libintl_gettext'
/home/1/axel/src/axel.c:301:(.text+0x796): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
axel.o:/home/1/axel/src/axel.c:345: more undefined references to libintl_gettext
axel.o：In function `axel_open':
/home/1/axel/src/axel.c:345:(.text+0x7df): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
/home/1/axel/src/axel.c:257:(.text+0x80a): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
axel.o：In function `axel_start':
/home/1/axel/src/axel.c:418:(.text+0xb10): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
/home/1/axel/src/axel.c:429:(.text+0xb60): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
/home/1/axel/src/axel.c:408:(.text+0xb88): relocation truncated to fit: R_X86_64_PC32 against undefined symbol libintl_gettext
axel.o：In function `axel_do':
/home/1/axel/src/axel.c:536:(.text+0xec8): additional relocation overflows omitted from the output
text.o：In function `main':
/home/1/axel/src/text.c:106: undefined reference to `libintl_setlocale'
/home/1/axel/src/text.c:107: undefined reference to `libintl_bindtextdomain'
/home/1/axel/src/text.c:108: undefined reference to `libintl_textdomain'
text.o：In function `print_version':
/home/1/axel/src/text.c:701: undefined reference to `libintl_gettext'
/home/1/axel/src/text.c:702: undefined reference to `libintl_gettext'
/home/1/axel/src/text.c:702: undefined reference to `libintl_gettext'
text.o：In function `print_help':
/home/1/axel/src/text.c:673: undefined reference to `libintl_gettext'
/home/1/axel/src/text.c:673: undefined reference to `libintl_gettext'
text.o:/home/1/axel/src/text.c:204: more undefined references to libintl_gettext
collect2: error：ld returned 1
make[2]: *** [Makefile:391：axel.exe] Error 1
make[2]: Leaving directory `/home/1/axel/src'
make[1]: *** [Makefile:483：all-recursive] Error 1
make[1]: Leaving directory `/home/1/axel'
make: *** [Makefile:380：all] Error 2

**Comment by ismaell** [comment]
Please provide more information, it sounds like a bug in the configure script. It's finding the headers but not linking against the right library, I'm guessing something assumes the symbols are in the libc.

El 15 de febrero de 2019 17:49:45 GMT+01:00, sdfww <notifications@github.com> escribió:
>I encountered an "undefined reference" error when compiling with
>Cygwin. It covers all versions after 2.5.>
>Only gettext v0.19 or higher is available in Cygwin.>
>Is this the problem and is there a solution?>
>>
>`$ make>
>make  all-recursive>
>make[1]: Entering directory `/home/1/axel'>
>Making all in src>
>make[2]:  `/home/1/axel/src'>
>  CC       axel.o>
>  CC       conf.o>
>  CC       conn.o>
>  CC       ftp.o>
>  CC       http.o>
>  CC       search.o>
>  CC       ssl.o>
>  CC       tcp.o>
>  CC       text.o>
>  CCLD     axel.exe>
>axel.o：In function `axel_open':>
>/home/1/axel/src/axel.c:224: undefined reference to `libintl_gettext'>
>/home/1/axel/src/axel.c:224:(.text+0x40b): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>/home/1/axel/src/axel.c:232: undefined reference to `libintl_gettext'>
>/home/1/axel/src/axel.c:232:(.text+0x456): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>/home/1/axel/src/axel.c:331: undefined reference to `libintl_gettext'>
>/home/1/axel/src/axel.c:331:(.text+0x6a4): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>/home/1/axel/src/axel.c:249: undefined reference to `libintl_gettext'>
>/home/1/axel/src/axel.c:249:(.text+0x758): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>/home/1/axel/src/axel.c:301: undefined reference to `libintl_gettext'>
>/home/1/axel/src/axel.c:301:(.text+0x796): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>axel.o:/home/1/axel/src/axel.c:345: more undefined references to
>libintl_gettext>
>axel.o：In function `axel_open':>
>/home/1/axel/src/axel.c:345:(.text+0x7df): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>/home/1/axel/src/axel.c:257:(.text+0x80a): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>axel.o：In function `axel_start':>
>/home/1/axel/src/axel.c:418:(.text+0xb10): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>/home/1/axel/src/axel.c:429:(.text+0xb60): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>/home/1/axel/src/axel.c:408:(.text+0xb88): relocation truncated to fit:
>R_X86_64_PC32 against undefined symbol libintl_gettext>
>axel.o：In function `axel_do':>
>/home/1/axel/src/axel.c:536:(.text+0xec8): additional relocation
>overflows omitted from the output>
>text.o：In function `main':>
>/home/1/axel/src/text.c:106: undefined reference to
>`libintl_setlocale'>
>/home/1/axel/src/text.c:107: undefined reference to
>`libintl_bindtextdomain'>
>/home/1/axel/src/text.c:108: undefined reference to
>`libintl_textdomain'>
>text.o：In function `print_version':>
>/home/1/axel/src/text.c:701: undefined reference to `libintl_gettext'>
>/home/1/axel/src/text.c:702: undefined reference to `libintl_gettext'>
>/home/1/axel/src/text.c:702: undefined reference to `libintl_gettext'>
>text.o：In function `print_help':>
>/home/1/axel/src/text.c:673: undefined reference to `libintl_gettext'>
>/home/1/axel/src/text.c:673: undefined reference to `libintl_gettext'>
>text.o:/home/1/axel/src/text.c:204: more undefined references to
>libintl_gettext>
>collect2: error：ld returned 1>
>make[2]: *** [Makefile:391：axel.exe] Error 1>
>make[2]: Leaving directory `/home/1/axel/src'>
>make[1]: *** [Makefile:483：all-recursive] Error 1>
>make[1]: Leaving directory `/home/1/axel'>
>make: *** [Makefile:380：all] Error 2>
>`>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/axel-download-accelerator/axel/issues/195

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdfww** [comment]
OK, This is my configuration:

Cygwin 2.11.2 (64-bit) -- Keep the default installation package
Additional installation package:
pkg-config 0.29.1-1
gettext 0.19.8.1-2
gettext-devel 0.19.8.1-2
libintl-devel 0.19.8.1-2
Autoconf 13-1
Autoconf2.5 2.69-4
Automake
Automake1.15
Automake 10-1
Automake1.15 1.15.1-1
gcc-core 7.4.0-1
make 4.2.1-2
openssl-devel 1.0.2p-1

Building:
$ cd axel-2.16.1
$ ./autogen.sh     ; Passed
$ ./configure     ; Passed
$ make     ; Failed

No changes were made to the Axel source code.

**Comment by ismaell** [comment]
Please attach the config log, it's probably guessing the `LDFLAGS` wrong, on most systems it must contain `-lintl`.

El 16 de febrero de 2019 8:05:37 GMT+01:00, sdfww <notifications@github.com> escribió:
>OK, This is my configuration:
>
>Cygwin 2.11.2 (64-bit) -- Keep the default installation package
>Additional installation package:
>pkg-config 0.29.1-1
>gettext 0.19.8.1-2
>gettext-devel 0.19.8.1-2
>libintl-devel 0.19.8.1-2
>Autoconf 13-1
>Autoconf2.5 2.69-4
>Automake
>Automake1.15
>Automake 10-1
>Automake1.15 1.15.1-1
>gcc-core 7.4.0-1
>make 4.2.1-2
>openssl-devel 1.0.2p-1
>
>Building:
>$ cd axel-2.16.1
>$ ./autogen.sh     ; Passed
>$ ./configure     ; Passed
>$ make     ; Failed
>
>No changes were made to the Axel source code.
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/axel-download-accelerator/axel/issues/195#issuecomment-464302495

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdfww** [comment]
1@a ~/axel
$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for off_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for getaddrinfo... yes
checking for gettimeofday... yes
checking for inet_ntoa... yes
checking for malloc... yes
checking for memset... yes
checking for nanosleep... yes
checking for realloc... yes
checking for select... yes
checking for setlocale... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strstr... yes
checking for strtoul... yes
checking for SSL... yes
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking build system type... x86_64-unknown-cygwin
checking host system type... x86_64-unknown-cygwin
checking for ld used by GCC... /usr/x86_64-pc-cygwin/bin/ld.exe
checking if the linker (/usr/x86_64-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... no
checking for iconv... no, consider installing GNU libiconv
checking for GNU gettext in libintl... yes
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... -lintl
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating po/Makefile.in
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile

1@a ~/axel

**Comment by ismaell** [comment]
There's a file named `config.log`, and please use a paste service (e.g.: dpaste.com).

**Comment by ismaell** [comment]
@sdfww can you try buliding again? The master branch added a related fix.

**Comment by ismaell** [comment]
Reopen if it's still an issue.

**Comment by Tom-python0121** [comment]
@ismaell , **The master branch added a related fix**,but I didn't find it in the version. Could you tell me exactly which version? This problem occurs in v2.17.1, v2.17.2, and v2.17.3. Other problems occur in later versions.

**Comment by ismaell** [comment]
Please always use the [latest release](../releases/latest) (2.17.10 at the moment), once a new version is released there's no more support for the previous ones.

**Comment by ismaell** [comment]
The version that fixed the linking order was 2.17.3, but that doesn't mean it fixes the whole problem, because I have no idea what the problem is. For figuring it out I would need the `config.log` file and a verbose build log (`make V=1`).

If it is correctly linking against `libintl`, then it would be useful to know where these symbols are defined if not there.
