### ISSUE TITLE
Set output file to stdout

### ISSUE THREAD

**Issue by rblaine95** [axel-download-accelerator/axel#199]
Is there a way to download with axel but, instead of saving the file downloaded to a file, just print the contents to stdout?

Similar to `wget $url -O-`?

**Comment by 097115** [comment]
So, you can't download to stdout, can you?

**Comment by rblaine95** [comment]
It's been 3 years, regretfully I genuinely can't remember

**Comment by ismaell** [comment]
No, it isn't possible.
