### ISSUE TITLE
Does it support to set cookie when download?

### ISSUE THREAD

**Issue by thinkycx** [axel-download-accelerator/axel#202]
I have seen the manual of it and it seems that it doesn't have this option.

**Comment by ismaell** [comment]
See <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie>.

**Comment by thinkycx** [comment]
I mean that does axel has the ability to set t cookie when download a file? e.g. 
$ axel --cookie "PHPSESSID=298zf09hf012fh2"  -n 10 URL 
@ismaell

**Comment by ismaell** [comment]
@thinkycx you can set the header, so yes; but it doesn't provide any syntactic sugar; patches are welcome.
