### ISSUE TITLE
LIBS synstax error

### ISSUE THREAD

**Issue by morcath** [axel-download-accelerator/axel#211]
I got error message:

> ./configure: line  7386: syntax error near unexpected token `LIBS="$PTHREAD_LIBS $LIBS"'
> ./configure: line 7386: `LIBS="$PTHREAD_LIBS $LIBS"

Here you can find log: https://justpaste.it/2aq8q

Do you have any idea what happend?

**Comment by makunterry** [comment]
please check whether `autoconf-archive` is installed in your system, if not, please install that package and re-run `autoreconf -i`.

**Comment by ismaell** [comment]
I answered by email but it seems it's bouncing. I've introduced the use of `AX_PTHREAD which is part of autoconf-archive.

**Comment by ismaell** [comment]
If you check the line you'll see the unexpanded macro before it.
