### ISSUE TITLE
TCP Fast Open Support

### ISSUE THREAD

**Issue by enihcam** [axel-download-accelerator/axel#213]
For example,
`setsockopt(fd, IPPROTO_TCP, TCP_FASTOPEN, &opt, sizeof(opt));`

**Comment by ismaell** [comment]
On client-side, `sendto` with `MSG_FASTOPEN` flag replaces connect and the first write.

**Comment by ismaell** [comment]
Alternatively, `TCP_FASTOPEN_CONNECT` can be used since Linux 4.11.
https://github.com/torvalds/linux/commit/19f6d3f3c8422d65b5e3d2162e30ef07c6e21ea2

**Comment by ismaell** [comment]
Our connection timeout support interferes with such implementation.
