### ISSUE TITLE
axel just reverts to --help output (no error message)

### ISSUE THREAD

**Issue by ringofyre** [axel-download-accelerator/axel#226]
$ axel http://dl1.upfdl.com/files/Serial/new/Sweetbitter/S01/Sweetbitter.S01E02.720p.WEB.HEVC.x265.RMT.Farda.DL.mkv
Usage: axel [options] url1 [url2] [url...]

--max-speed=x		-s x	Specify maximum speed (bytes per second)
--num-connections=x	-n x	Specify maximum number of connections
--output=f		-o f	Specify local output file
--search[=x]		-S [x]	Search for mirrors and download from x servers
--header=x		-H x	Add header string
--user-agent=x		-U x	Set user agent
--no-proxy		-N	Just don't use any proxy server
--insecure		-k	Don't verify the SSL certificate
--quiet			-q	Leave stdout alone
--verbose		-v	More status information
--alternate		-a	Alternate progress indicator
--help			-h	This information
--version		-V	Version information

Visit https://github.com/eribertomota/axel/issues to report bugs

alias is axel -n 10 -cva, still doesn't work with alias disabled - can't even get -V output

$ uname -a
Linux Pavillion 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux

wget gets files.

**Comment by ismaell** [comment]
That's an old version, looks like v2.13.1; try updating it.

**Comment by ismaell** [comment]
Not happening on 2.17; but the server is returning a 500 error code.
