### ISSUE TITLE
Please, make manpages generation reproducible

### ISSUE THREAD

**Issue by eribertomota** [axel-download-accelerator/axel#230]
Dear developer,

The current manpage build system generate non-reproducibles manpages, because the date is variable. On Debian, each architecture produces the .deb file in a different time. So, each manpage may have a different date.

Regards,

Eriberto

**Comment by ismaell** [comment]
Hi Eriberto,

I will check, the intention was for the date to be read from the VERSION file.

BR,

**Comment by eribertomota** [comment]
Thanks!

Em sex, 26 de jul de 2019 às 22:28, Ismael Luceno <notifications@github.com>
escreveu:

**Comment by ismaell** [comment]
I can't reproduce the issue, but maybe it's something slippery... what's the date you've got on the generated manpage?

**Comment by eribertomota** [comment]
Em sáb, 27 de jul de 2019 às 18:08, Ismael Luceno <notifications@github.com>
escreveu:

> I can't reproduce the issue, but maybe it's something slippery... what's
> the date you've got on the generated manpage?
>

 27 July 2019

I confirmed it in Debian packages:

1. Go to https://packages.debian.org/unstable/axel#pdownload

2. Download a package.

3. Open: # ar -x package.deb

4. Untar data: tar -xvf data.tar.xz

5. Open a manpage.

Regards,

Eriberto

**Comment by ismaell** [comment]
I figured it out. It's a bug on the Makefile. I'll fix it later today.
