### ISSUE TITLE
Files forgotten by clean

### ISSUE THREAD

**Issue by eribertomota** [axel-download-accelerator/axel#231]
Hi @ismaell 

After a distclean, the following files are being kept in source code: doc/axel.1 e po/axel.pot

Thanks!

Eriberto

**Comment by ismaell** [comment]
These are part of the distribution tarball, that's why they're not cleaned up.

Why do you need them removed? both should be invariant.

**Comment by ismaell** [comment]
```sh
$ tar --wildcards -tvf axel-2.17.5.tar.bz2 '*.pot' '*.1'
-rw-r--r-- 1000/1000      5827 2019-07-23 19:50 axel-2.17.5/doc/axel.1
-rw-r--r-- 1000/1000      7568 2019-07-23 19:50 axel-2.17.5/po/axel.pot

**Comment by eribertomota** [comment]
Em ter, 30 de jul de 2019 às 08:10, Ismael Luceno <notifications@github.com>
escreveu:

> $ tar --wildcards -tvf axel-2.17.5.tar.bz2 '*.pot' '*.1'
> -rw-r--r-- 1000/1000      5827 2019-07-23 19:50 axel-2.17.5/doc/axel.1
> -rw-r--r-- 1000/1000      7568 2019-07-23 19:50 axel-2.17.5/po/axel.pot
>
>
I am using the tarball generated by GitHub over the original source code
when releasing a new version[1]. This tarball have not the files. Don't
worry because I can adjust it in packaging[2].

[1] https://github.com/axel-download-accelerator/axel/archive/v2.17.5.tar.gz
[2] https://salsa.debian.org/debian/axel/blob/debian/master/debian/clean

Cheers,

Eriberto

**Comment by ismaell** [comment]
Ahhh, I see now, you didn't take my advice before... :-/. Those are snapshots, not release tarballs (i.e. the result of `make dist`).

**Comment by ismaell** [comment]
You're doing it wrong, you _must_ use the tarball generated by `make dist`, or (not a good idea) run `make distdir` first, then repeat your build inside the generated distribution directory.

**Comment by ismaell** [comment]
This distinction between snapshots and release tarballs is extremely important. You can always get a release out of the snapshot, but you have to follow the same steps, just as if you were making a release.
