### ISSUE TITLE
Make the "alternate" progress indicator the default.

### ISSUE THREAD

**Issue by pthfdr-42** [axel-download-accelerator/axel#234]
The default progress indicator is pointless. It spams dots to the terminal, effectively trashing the scrollback buffer; also, it actually shows less information than the "alternate" ones in `-a`.
The only thing good about the default one is that it works on a dumb terminal and is visible in scripts, but in either case, the user would disable the indicator as it spams dots.

I think that you should:
1. Remove the default indicator and make the "alternate" one the default.
2. If a non-interactive shell is detected, disable the indicator entirely.

**Comment by ismaell** [comment]
I agree the default isn't useful, but some sort of feedback is needed. My preference would be for something easy for both humans and programs to parse. Ideas?

**Comment by pthfdr-42** [comment]
Simple. Here is my suggestion:
Every second it prints the amount downloaded in that second (AKA download speed), and the progress.
Mockup:

    $ axel hxxp://1.2.3.4/sample.bin
    AXEL v1.2.3.4
    File: sample.bin [15000]: 
    4000/15000 [4000]
    6000/15000 [2000]
    8500/15000 [2500]
    10000/15000 [1500]
    12000/15000 [2000]^C
    ERROR: SIGTERM received.
    $ axel hxxp://1.2.3.4/sample.bin
    File: sample.bin
    Continue: 12000/15000
    14000/15000 [2000]
    15000/15000 [1000]
    Completed: sample.bin

**Comment by ismaell** [comment]
That's unusable. To be viable it needs to provide more information, so we can build a live progress report out of it. It needs to show how much _each thread_ is doing and the position of that progress.

To be acceptable it also needs to come with an implementation.

**Comment by ismaell** [comment]
Or, alternatively, a bounty and some detailed acceptance criteria.

**Comment by giovanism** [comment]
I think the points is to not spam the tty with dots under default interactive behavior. We can leave the old output for non-tty output and use the `-a` output as default for interactive session. I think the chance of this breaking people's existing scripts is minimal and there is no need to wait for major version revision.

**Comment by ismaell** [comment]
@giovanism patch?

**Comment by ismaell** [comment]
Just to clarify, I'm not doing it precisely because it's easy and I have better things to do at the moment.

**Comment by HapCoderWei** [comment]
I will give a patch to implement this advice: 
`1. Remove the default indicator and make the "alternate" one the default`
Is that change ok?

**Comment by ismaell** [comment]
Changing the default depending if stdin is a tty is ok, that should be enough.

**Comment by HapCoderWei** [comment]
This  issue can be closed.
