### ISSUE TITLE
How to build standalone?

### ISSUE THREAD

**Issue by HapCoderWei** [axel-download-accelerator/axel#235]
Hi, I want to build search.c into  a exec file standalone, as i see there have a STANALONE Macro in search.c file. My question is how i can build this file into a stanalone exec program?  Should I add some macro defines in configure.ac or m4 file? I'm a newbie in autotools. Could you give me some advise? 
Best Wishes!

PS: I'm learning this project, and want to see how the search.c file is running.

**Comment by ismaell** [comment]
The macro is meant to be defined when compiling the file manually; it's not intended to be used by the build system.
