### ISSUE TITLE
Error opening local file

### ISSUE THREAD

**Issue by Alice-space** [axel-download-accelerator/axel#238]
![image](https://user-images.githubusercontent.com/47878052/66548621-333ed400-eb74-11e9-8090-0439c4acfbf6.png)
Help!
I cannot use axel because Error opening local file as the picture shown above.

**Comment by Alice-space** [comment]
After reboot, i successfully solved that question 
Don`t know why ........

**Comment by aruiplex** [comment]
I found the same issue with you but after I reboot it is still not working. Do you found something after that? thanks
