### ISSUE TITLE
Fail when disk is full

### ISSUE THREAD

**Issue by eribertomota** [axel-download-accelerator/axel#24]
Hi,

After a disk full, Axel is sending the following message:

Initializing download: http://xyz/1GB.zip
File size: 1073741824 bytes
axel: axel.c:190: axel_open: Assertion `nread == sizeof( axel->conf->num_connections )' failed.
Aborted

IMO, the best way is show a 'Disk full' message.

Cheers,

Eriberto

**Comment by pan-long** [comment]
Hi Eriberto,

I am not a native English speaker. What exact message do you think is the best?

Cheers,
Pan Long

**Comment by ordex** [comment]
Actually that message happens because axel is trying to open a bogus state file (probably bogus because it couldn't be written properly as there s no space on disk). But generally speaking proper checks of this kind are missing.
