### ISSUE TITLE
High CPU usage and memory leak.

### ISSUE THREAD

**Issue by abcfy2** [axel-download-accelerator/axel#246]
I use the latest git version. But I find axel cost too much memory with high cpu usage.

```bash
# LANG=en axel --version
Axel version 2.17.6+g657514 (linux-gnu)

Copyright 2001-2007 Wilmer van der Gaast,
	  2007-2009 Giridhar Appaji Nag,
	  2008-2010 Philipp Hagemeister,
	  2015-2017 Joao Eriberto Mota Filho,
	  2016-2017 Stephen Thirlwall,
	  2017      Ismael Luceno,
	  2017      Antonio Quartulli,
		    and others.
Please, see the CREDITS file.
```

```
axel -an 10 large_file_and_long_time_for_downloading
```

```
ps aux | grep axel
root     12030 100.1  70.2 6000024 5316540 pts/1 Rl+  01:07   2:53 axel -an 10 xxxxxx
```

You can see axel use 100% cpu (24 cores) and 70.2% memory (64GB), I have to kill the axel to release memory usage.

**Comment by ismaell** [comment]
Which OS is it?

I haven't seen that on my systems,  but maybe there's some assumption that doesn't hold on yours.

Could you compile it with debug information and provide a perf trace of the run?

If you need a GUI I recommend this one: https://github.com/KDAB/hotspot

I need to see which functions are involved to know where to start looking.

**Comment by abcfy2** [comment]
Both CentOS 7.6 and Deepin 15.11 (based on Debian 9) have this issue.

**Comment by abcfy2** [comment]
`perf.data` is too large, I just record some minutes with 15GB. And I find the axel memory usage will never reduce. Here is the result:

![深度截图_dde-desktop_20191028194416](https://user-images.githubusercontent.com/5327677/67676000-8e1d5b80-f9bb-11e9-8391-23655edd2e1a.png)
![深度截图_dde-desktop_20191028194407](https://user-images.githubusercontent.com/5327677/67676001-8e1d5b80-f9bb-11e9-8bcb-770695fcdced.png)
![深度截图_dde-desktop_20191028194424](https://user-images.githubusercontent.com/5327677/67676003-8eb5f200-f9bb-11e9-8792-544437417c8f.png)
![深度截图_dde-desktop_20191028194334](https://user-images.githubusercontent.com/5327677/67676004-8f4e8880-f9bb-11e9-810c-31460c79388c.png)
![深度截图_dde-desktop_20191028194346](https://user-images.githubusercontent.com/5327677/67676005-8f4e8880-f9bb-11e9-92de-516327366c5b.png)

**Comment by ismaell** [comment]
That's very weird.

We would need to know the return values of the `select` in `axel_do` and the `tcp_read` on the block following it.

It looks like it's continuously looping without doing useful work.

Things that may be relevant:
- is it an HTTPS connection?
- does your system support TCP FASTOPEN_CONNECT?

**Comment by abcfy2** [comment]
- Yes, it's https connection.
- Deepin 15.11 use `4.15` kernel, and CentOS 7 use `3.10.0-1062.4.1` kernel, I thins both support TCP FASTOPEN_CONNECT

**Comment by ismaell** [comment]
`TCP_FASTOPEN_CONNECT` was added in Linux 4.11 IIRC, so it's probably not that. If you want to test with it disabled, you can compile with `CFLAGS=-DTCP_FASTOPEN_CONNECT=0 ...`.

I'm not sure it's a regression, so maybe it's not worth doing a `git bisect` right away... do you know how to use a debugger? that's the easiest way to get the return values to try to see what's going on between the `select` and the read.

**Comment by abcfy2** [comment]
No. I don't know how to do this. Would you give me a help? I find the `2.17.6` still has this issue.

**Comment by ismaell** [comment]
Then maybe try running it with `ltrace`, and upload the log somewhere and post a link here; we probably need just a few seconds. I'll have some time tomorrow night to review the issue.

**Comment by abcfy2** [comment]
OK. Hope this issue could be fixed soon. :)

**Comment by abcfy2** [comment]
Any update? I find the Windows version has the same issue.

Windows version can install msys2 and use: `pacman -S axel` to install the Windows version, with the same issue

**Comment by ismaell** [comment]
You have to re-build axel from sources; something like this would do:
```
CFLAGS="-DTCP_FASTOPEN_CONNECT=0 -Og -g" ./configure && make
```

With that you make sure FASTOPEN isn't used and that the binary gets debugging information.

`ltrace -S -f -tt -T -o axel.trace.log ./axel url` would give you useful information about where time is being spent.

Another uselful piece of information could come from a dump of the state; those can be produced by `gcore`, you just run `gcore pid_of_axel`; you can do several if you notice a change, it just stops the execution, makes the dump, and continues it.

I really can't reproduce this anywhere... but with a full trace and at least one core dump the issue may become tractable. I don't doubt there's many corner cases not being handled properly around thread management.

**Comment by abcfy2** [comment]
Hi @ismaell . I try to build with `CFLAGS="-DTCP_FASTOPEN_CONNECT=0 -Og -g"`, but it will cause segment fault.

```
LANGUAGE=C.UTF-8 ltrace -S -f -tt -T -o axel.trace.log ./axel -an 50 myurl
State file found: 5943284 bytes downloaded, 13844390955 to go.
Starting download

Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Connection gone.
Segment fault
```

And here is trace log.

[axel.trace.log.gz](https://github.com/axel-download-accelerator/axel/files/3930202/axel.trace.log.gz)

**Comment by abcfy2** [comment]
Without `ltrace` seems OK. Here is `gcore` output:

[core.19191.gz](https://github.com/axel-download-accelerator/axel/files/3930234/core.19191.gz)

**Comment by abcfy2** [comment]
Strange. I can't reproduce this issue right now. So close this issue for now, and waiting for the right way to reproduce this issue.

**Comment by ismaell** [comment]
Ok for me, so far I haven't seen the issue anywhere...
