### ISSUE TITLE
will axel add a recursive download mode to download a folder?

### ISSUE THREAD

**Issue by 1160300929** [axel-download-accelerator/axel#252]

**Comment by ismaell** [comment]
short answer is: no

it doesn't fit the way it's coded, it could be implemented if we do some refactoring, but that will not happen anytime soon.

El January 7, 2020 12:28:06 PM UTC, "郑小燮" <notifications@github.com> ha escrit:
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/axel-download-accelerator/axel/issues/252
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mohitjoshi155** [comment]
ya i also need this

**Comment by ismaell** [comment]
> ya i also need this

Feel free to implement it then.
