### ISSUE TITLE
Cryptic configure error with mingw64

### ISSUE THREAD

**Issue by SamLukeYes** [axel-download-accelerator/axel#253]
while running './configure' in git bash, an error appeared like this:
configure: error:  is required.

[config.log](https://github.com/axel-download-accelerator/axel/files/4038999/config.log)

**Comment by ismaell** [comment]
mingw isn't officially supported. patches are welcome

**Comment by ismaell** [comment]
at that point it's failing to find headers for the bsd sockets library

**Comment by ismaell** [comment]
a pthreads implementation will be needed too
