### ISSUE TITLE
Can't handle URLs of length over 1024

### ISSUE THREAD

**Issue by xindubawukong** [axel-download-accelerator/axel#254]
Error: "Can't handle URLs of length over 1024."
I fail to download because the url is too long. Can someone fix this?

**Comment by xindubawukong** [comment]
Version: Axel version 2.17.6 (darwin18.7.0)

**Comment by DanBrown47** [comment]
This is not complete the issue is persisting in the latest version too.

@xindubawukong Why did you close this as complete ?
