### ISSUE TITLE
tarballs and "source code" tarball behave differently

### ISSUE THREAD

**Issue by cslycord** [axel-download-accelerator/axel#258]
In the project dependencies list, txt2man is listed as an "extra dependency for building from snapshots". 

But in releases, if I download the "Source code (tar.gz)" [ https://github.com/axel-download-accelerator/axel/archive/v2.17.7.tar.gz ] this file doesn't contain manpages and needs txt2man to build.

But if I download the tar.gz above that [ https://github.com/axel-download-accelerator/axel/releases/download/v2.17.7/axel-2.17.7.tar.gz ], the file contains manpages and doesn't need txt2man to be built.

**Comment by ismaell** [comment]
It is expected. The tarballs coming from the `*/archive/` URLs are effectively snapshot tarballs, and Github provides no way to suppress their links from the release pages.
