### ISSUE TITLE
Does  axel  support  http/1.1 or 2.0 ?

### ISSUE THREAD

**Issue by jih488** [axel-download-accelerator/axel#264]
Does  the axel 2.17   support  http/1.1  or 2.0?

**Comment by ismaell** [comment]
On 20/Mar/2020 07:45, jih488 wrote:
> Does  the axel 2.17   support  http/1.1  or 2.0?

HTTP/1.0 with extensions from HTTP/1.1. Full HTTP/1.1 support would be
nice.
