### ISSUE TITLE
I got  SSL error: Certificate error  even after adding -k 

### ISSUE THREAD

**Issue by SalimF** [axel-download-accelerator/axel#274]
Hi this happened to me with version 2.6.! so I  decide to compile the newer version 2.17.7 but I still got same error message 
`axel SSL error: Certificate error`
I tried both   `--insecure` and  `-k` with the same error message how get axel ignore SSL certificate (BTW the certificate is valid ).

**Comment by SalimF** [comment]
Update the issue dose not exist with the version `2.16.1` that shipped with my distro `Linux mint 19` this may be due the compiling configuration I made "I don't know " any way this is the path of distro version 2.16.1 and this is the path for complied one `/usr/local/bin/axel`  .

**Comment by ismaell** [comment]
@SalimF OK. In case of old versions it's recommended to just fill the bug with your distribution stating which versions show the bug and which ones don't, so maybe they backport the patch or update it. From the project side there's nothing we can do in this case other than tracking them. If you open it, please link it here.

**Comment by fritruc** [comment]
I have this issue in a debian docker container, with the v2.17.8 of axel
When using -k, I got this error :
> axel -k  https://github.com
> >SSL error: Certificate error

**Comment by ismaell** [comment]
Confirmed.

**Comment by DonRichards** [comment]
I'm getting the same error from a fresh install using `$ brew install axel` installs v2.17.8 

Axel -k is still giving me the same error.

**Comment by Jason23347** [comment]
> I'm getting the same error from a fresh install using `$ brew install axel` installs v2.17.8
> 
> Axel -k is still giving me the same error.

@DonRichards This was fixed in 80f8a5a, after the 2.17.8 release.

**Comment by DonRichards** [comment]
@Jason23347 I understand that but.... who ever manages the homebrew installs package should be notified to update their repo so brew will pull the latest update or a version release with a brew package update. I'm not sure how brew packages work.

**Comment by ismaell** [comment]
I've been quite busy so I couldn't make a release yet. But I'm fixing that right now. Hopefully homebrew will catch it quickly.

**Comment by damdev** [comment]
Axel version 2.17.6 has this bug too.

**Comment by Mahtabctg** [comment]
Same issue on Axel version 2.17.8:

/media/datapartition # axel -k -n 8 https://download3.vmware.com/software/fusion/file/VMware-Fusion-11.5.3-15870345.dmg
Initializing download: https://download3.vmware.com/software/fusion/file/VMware-Fusion-11.5.3-15870345.dmg
SSL error: Certificate error

/media/datapartition # axel -V
Axel version 2.17.8 (linux-gnu)

Copyright 2001-2007 Wilmer van der Gaast,
          2007-2009 Giridhar Appaji Nag,
          2008-2010 Philipp Hagemeister,
          2015-2017 Joao Eriberto Mota Filho,
          2016-2017 Stephen Thirlwall,
          2017      Ismael Luceno,
          2017      Antonio Quartulli,
                    and others.
Please, see the CREDITS file.

**Comment by ismaell** [comment]
@damdev @Mahtabctg This bug was fixed in 2.17.9.
