### ISSUE TITLE
Cannot compile v2.17.8 with OpenSSL 1.0.2k on CentOS 7

### ISSUE THREAD

**Issue by xkszltl** [axel-download-accelerator/axel#289]
CentOS 7 shipped with OpenSSL 1.0.2k by default.
We were able to compile axel previously (~1 week ago) on it but same build script failed today:
```
error: passing argument 1 of ‘X509_get_subject_name’ discards ‘const’ qualifier from pointer target type
```
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/5203025/78897520-e72e0700-7aa4-11ea-9155-487a10d2f15e.png">

Same script works on Ubuntu 18.04/OpenSSL 1.1.1

**Comment by ismaell** [comment]
@xkszltl there's a configure flag for disabling errors: 
```
  --disable-Werror        Unconditionally make all compiler warnings non-fatal
```

These errors should not cause ABI incompatibilities, but should be solved by the distribution anyway.

You should open a bug report with CentOS (or find an existing one, maybe there is) against their OpenSSL package, and attach it there, then reference that bug report here.

Anyway, please tell us how it went when disabling `-Werror`.

**Comment by xkszltl** [comment]
Works without Werror.
