### ISSUE TITLE
It can't success download big file.

### ISSUE THREAD

**Issue by noveljava** [axel-download-accelerator/axel#291]
OS : Mac
Version : Axel version 2.17.8 (darwin19.4.0)

> Copyright 2001-2007 Wilmer van der Gaast,
	  2007-2009 Giridhar Appaji Nag,
	  2008-2010 Philipp Hagemeister,
	  2015-2017 Joao Eriberto Mota Filho,
	  2016-2017 Stephen Thirlwall,
	  2017      Ismael Luceno,
	  2017      Antonio Quartulli,
		    and others.
Please, see the CREDITS file.

---
I try to download 90GB file. But It remind some file size and not working.

> File size: 97081919849 bytes
Opening output file ____.tar.gz
State file found: 97081642103 bytes downloaded, **277746 to go**.

I waiting for to success download during all night, but It don't success.
Who know similar issue?

**Comment by ismaell** [comment]
We will need more information to solve the issue. Can you provide a syscall trace?

**Comment by noveljava** [comment]
How to get syscall trace information?

**Comment by ismaell** [comment]
On Darwin you can use `dtruss`, see the manual page.

**Comment by ismaell** [comment]
was it solved by 2.17.9/10???
