### ISSUE TITLE
Feature: Do not download, when file exist with same size.

### ISSUE THREAD

**Issue by Saentist** [axel-download-accelerator/axel#296]
Is there a way to make check if file with want to download exist in location for download it.
Also to make check if existing file exist, but is with different size, and if is different to download.

This will be useful when downloading with unstable connection lot of files and restarting batch not continue from when it losing connection, and re-download already finished downloads.

**Comment by ismaell** [comment]
There is the `-c` option that avoids downloading the file if it already exists and there is no state file; it does however not check if the file is smaller.

**Comment by Saentist** [comment]
So 50% ;)
File size difference is important!

**Comment by ismaell** [comment]
On 04/May/2020 04:59, Saentist wrote:
> So 50% ;)
> File size difference is important!

Well, this only affects the case where you started with one tool and
then switched to Axel... otherwise the files will have a companion state
file.

**Comment by Saentist** [comment]
when download file with size each day change but name is same 
comparing local and remote size in this case is panacea.

**Comment by ismaell** [comment]
On 04/May/2020 05:25, Saentist wrote:
> when download file with size each day change but name is same 
> comparing local and remote size in this case is panacea. 

I would accept a patch to support that, sure, but it's not a feature
that I'm looking after. Currently it's not even supported in the case of
incomplete downloads with corresponding state files.

**Comment by Saentist** [comment]
You misunderstood me.
Case is  download is complete in first download. 

For example in my case is database with is near static until some add new data with increase size (but this can happen in range of 1 day or 2 weeks)
So if I download this file in 23:59 each day, and previous time file is with same size as now, do I need to download twice same file?

**Comment by ismaell** [comment]
On 04/May/2020 07:00, Saentist wrote:
<...>
> So if I download this file in 23:59 each day, and previous time file
> is with same size as now, do I need to download twice same file?

Not only it would be tricky to implement (there's some missing pieces on
axel's side), but more importantly, maybe the file is different but has
the same size.  It can't be made safe for non-static files.

If you trust the server, you could put together a script, using some
other tool to make a HEAD request, and compare it's output to the file,
then run axel if required.
