### ISSUE TITLE
Error while waiting for connection: Invalid argument

### ISSUE THREAD

**Issue by kwhiteaker** [axel-download-accelerator/axel#306]
Hi, when using Axel version 2.17.5 to download a tarball on Ubuntu 20.04, I get the following error:
```
kelton:~/$ axel -n 10 https://launchpad.net/madanalysis5/trunk/v1.7/+download/ma5_v1.8.44.tgz
Initializing download: https://launchpad.net/madanalysis5/trunk/v1.7/+download/ma5_v1.8.44.tgz
File size: 790501 bytes
Opening output file ma5_v1.8.44.tgz.0
Server unsupported, starting from scratch with one connection.
Starting download

Error while waiting for connection: Invalid argument

Downloaded 0 byte(s) in 0 second(s). (0.00 KB/s)
```

And then after failing like this, the return code is zero:
```
kelton:~/$ echo $?
0
```

Edit: wget successfully downloads the same file.

**Comment by wtywtykk** [comment]
I encountered this problem with WSL Ubuntu 20.04 on Windows 10 2004. The default WSL version is WSL 1, and it doesn't support the nanosleep call. https://github.com/microsoft/WSL/issues/4898 .

Updating to WSL 2 will solve this problem.
https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2

Or alternately, use Ubuntu 18.04. It doesn't have such problem.

**Comment by ismaell** [comment]
@kwhiteaker are you using WSL?

**Comment by ismaell** [comment]
Seems to be an issue with WSL1 only, which I can't support anyway, so I'm closing it.
