### ISSUE TITLE
Axel 2.17.9: FTBFS in Debian Sid

### ISSUE THREAD

**Issue by eribertomota** [axel-download-accelerator/axel#311]
Hi @ismaell,

Axel 2.17.9 Fail to Build From Source in my machine with Debian Sid with GCC-9/10:

```
gcc -DHAVE_CONFIG_H -I.  -DLOCALEDIR=\""/usr/share/locale"\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2 -pthread -fno-strict-aliasing -Wnested-externs -Wmissing-prototypes -Wstrict-prototypes -Wdeclaration-after-statement -Wimplicit-function-declaration -Wold-style-definition -Wjump-misses-init -Wall -Wextra -Wundef -Wwrite-strings -Wpointer-arith -Wmissing-declarations -Wredundant-decls -Wno-unused-parameter -Wno-missing-field-initializers -Wformat=2 -Wcast-align -Wformat-nonliteral -Wformat-security -Wsign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Wmissing-noreturn -Winit-self -Wmissing-include-dirs -Wunused-but-set-variable -Warray-bounds -Wreturn-type -Wswitch-enum -Wswitch-default -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wdouble-promotion -Werror -Wno-suggest-attribute=format -Wno-error=unused-parameter -Wno-error=missing-field-initializers -Wno-declaration-after-statement -Wno-error=cast-align -Wno-error=inline -g -O2 -fdebug-prefix-map=/PKGS/axel/axel=. -fstack-protector-strong -Wformat -Werror=format-security -c -o src/conn.o src/conn.c
src/axel.c: In function ‘save_state’:
src/axel.c:790:10: error: variable ‘nwrite’ set but not used [-Werror=unused-but-set-variable]
  790 |  ssize_t nwrite;
      |          ^~~~~~
```

Regards,

Eriberto

**Comment by ismaell** [comment]
@eribertomota are you building from the tarballs or from the repo?

**Comment by eribertomota** [comment]
The Debian package gets the new version via uscan command. The rule is here[1].

[1] https://sources.debian.org/src/axel/2.17.8-1/debian/watch/

So, when I run uscan-check, I get:

```
uscan: Newest version of axel on remote site is 2.17.9, local version is 2.17.8
uscan:    => Newer package available from
      https://github.com/axel-download-accelerator/axel/releases/download/v2.17.9/axel-2.17.9.tar.xz
uscan info: Scan finished
```

Consequently I am using a tarball from "download" section in project.

Eriberto


Eriberto

**Comment by ismaell** [comment]
I ask because `-Werror` is only added by default when building from the repo. Is somehow a git repo being created out of the tarball by the build process? if so you have no option but to add `--disable-Werror` to the configure script flags.

**Comment by eribertomota** [comment]
> I ask because `-Werror` is only added by default when building from the repo. Is somehow a git repo being created out of the tarball by the build process? if so you have no option but to add `--disable-Werror` to the configure script flags.

Yes, since 2016 Debian build system always run autoconfigure -fi (via dh_reconfigure).

I added --disable-Werror to dh_auto_configure and Axel builds fine now. I suggest put it in README.md.

Feel free to close this issue.

Eriberto
