### ISSUE TITLE
Is bugged -k option?

### ISSUE THREAD

**Issue by eribertomota** [axel-download-accelerator/axel#312]
Hi @ismaell,

On my machine, the following command works fine:

axel https://people.debian.org/~eriberto/tests-axel/test.img

However, the following command fails:

axel -k https://people.debian.org/~eriberto/tests-axel/test.img
Initializing download: https://people.debian.org/~eriberto/tests-axel/test.img
SSL error: Certificate error

I think axel should ignore the certificate in last case. Am I wrong? This behaviour is genrating issues in CI tests in Debian.

Regards,

Eriberto

**Comment by ismaell** [comment]
Fixed in commit 80f8a5a030792a65b846cff6b62f6aebb1da6f2f.

**Comment by eribertomota** [comment]
Dear @ismaell,

You closed the issue suddenly without interact with me. Please, be polite and respectful.

I am using Debian Sid and Axel 2.17.9. Maybe I  am doing something wrong but I need to know. Can you, please, test my commands and explain the problem or say me "I can't reproduce the error"?

Eriberto

**Comment by ismaell** [comment]
```
$ axel --version
Axel 2.17.9 (linux-musl)

Copyright 2001-2007 Wilmer van der Gaast,
          2007-2009 Giridhar Appaji Nag,
          2008-2010 Philipp Hagemeister,
          2015-2017 Joao Eriberto Mota Filho,
          2016-2017 Stephen Thirlwall,
          2017      Ismael Luceno,
          2017      Antonio Quartulli,
                    and others.
Please, see the CREDITS file.



$ axel -k  https://google.com
Initializing download: https://google.com
File size: unavailable
Opening output file default.4
Server unsupported, starting from scratch with one connection.
Starting download

Connection 0 finished

Downloaded 12.7725 Kilobyte(s) in 0 second(s). (42.33 KB/s)
```

**Comment by ismaell** [comment]
There's something really odd, because the bug existed *before* 2.17.9.

**Comment by eribertomota** [comment]
Ok, I was testing in 2.17.8, not 2.17.9, because the last version wasn't building. A mistake mine. However, is not acceptable close the door in my face. Please, be patient in next time. I am trying to make the best for Axel in Debian and -k option was impacting in CI tests. I am not a newbie but I have doubts sometimes.

Regards,

Eriberto
