### ISSUE TITLE
Can connection number be reset?

### ISSUE THREAD

**Issue by kingaza** [axel-download-accelerator/axel#320]
For example, I set n=10 at the beginning. Then I think the downloading was still a little bit slow, so I terminated the downloading, and rerunned axel with n=20. However, the downloading speed was still the same as the first try.
But if I do downloading with n=20 at the beginning, the speed can be twice as n=10.
My question is, can I increase the speed in the case of recover?

Thx a lot.

**Comment by ismaell** [comment]
On August 25, 2020 2:03:53 AM UTC, kingaza <notifications@github.com> wrote:
>For example, I set n=10 at the beginning. Then I think the downloading was still a little bit slow, so I terminated the downloading, and rerunned axel with n=20. However, the downloading speed was still the same as the first try.
>But if I do downloading with n=20 at the beginning, the speed can be twice as n=10.
>My question is, can I increase the speed in the case of recover?
>
>Thx a lot.
>

The number of threads is fixed and can't be changed dynamically; by restarting a download Axel takes the same configuration of the initial instance.

**Comment by kingaza** [comment]
OK, I will increase the connection number and re-download.
Thank you very much.
