### ISSUE TITLE
incomplete downloads

### ISSUE THREAD

**Issue by gumptioncreek** [axel-download-accelerator/axel#321]
When attempting to download using the -n option to specify the maximum number of connections, the download almost finishes leaving one byte not downloaded from the end of the data each connection is responsible to download. The undownloaded bytes are located in the partially downloaded file at the following locations: 1 times file_length divided by max_connections - 1, 2 times file_length divided by max_connections, 3 times file_length divided by max_connections + 1, 4 times file_length divided by max_connections + 2, 5 times file_length divided by max_connections + 3, etc for the first max_connections-1 bytes. The location of the final byte that fails to download is the last byte of the file. The value of bytes that fail to download other than the last byte (which is simply missing entirely), is zero. as an example if using the option "-n 33" there will be 33 bytes that fail to download and the second to the last failed byte is located at 32 times file_length divided by max_connections + 30. This assumes that the file being downloaded is larger than the value for max_connections since this was the only scenario tested.

**Comment by ismaell** [comment]
I haven't seen this issue in recent versions. Please reopen if it still happens in some corner case.
