### ISSUE TITLE
Wish: Report file sizes in appropriate magnitudes (like df -h or du -h)

### ISSUE THREAD

**Issue by thegreyshadow** [axel-download-accelerator/axel#326]
```
Initializing download: xxxxxxxx
File size: 553175400 bytes
```

Thanks for developing axel. It's an incredible piece of software and it's quickly becoming my primary download manager, taking over wget, curl, and even aria2!

I would like to request a feature. As shown in the preformatted output, axel reports the file size in bytes. However, axel is also prepared for downloading big large files, so for such files, reporting the file size in bytes would be difficult to assess or understand.

Thus I would like to suggest the following:
1. Keep the default behavior as it is.
2. Put a commandline switch which would have an effect similar to what the `-h` switch does to utilities such as `du` or `dh`; that is, provide file sizes in "human-understandable" magnitudes. Under such switch, instead of reporting this file as 553175400 bytes, axel would report it as 528 MiB or something similar.
3. Alternatively, any magnitude of file sizes could be formatted so that it could be separated in groups of thousands. Thus, instead of 553175400 bytes, axel would report it as *553 175 400* bytes.

Thanks again,

Eduardo

**Comment by ismaell** [comment]
I think there's no danger in changing the behavior w/o introducing any command line switches, as it already does print the "human-readable" form after finishing the download, so it should do the same at the beginning.
