### ISSUE TITLE
Using Axel returns "Too Many Redirects" error when trying to download.

### ISSUE THREAD

**Issue by seanswyi** [axel-download-accelerator/axel#339]
It seems that this issue was addressed before and solved in [#3](https://github.com/axel-download-accelerator/axel/issues/3) but I'm not able to see how it was fixed.

My Axel version is 2.5 and I'm trying to run the command:

```
axel https://dumps.wikimedia.org/wikidatawiki/entities/20210104/wikidata-20210104-all-BETA.nt.bz2
```

which gives me the output:

```
Initializing download: https://dumps.wikimedia.org/wikidatawiki/entities/20210104/wikidata-20210104-all-BETA.nt.bz2
Too many redirects.
```

What may be causing the issue, and how can I fix it? Any pointers to where I should look are also appreciated.

**Comment by ismaell** [comment]
That version is from 5 years ago.
