### ISSUE TITLE
Feature Request: Add option to not download if already done, like `wget -c`

### ISSUE THREAD

**Issue by AKarbas** [axel-download-accelerator/axel#341]
Btw, thanks for the great work :)

This (the option to not redownload if not needed) is especially helpful if axel is used to download multiple files, e.g., in
```shell
for x in {01..33}; do axel -van8 https://site.com/uploads/file-${x}.zip; done
```
If the downloads are stopped for some reason, I want to re-run the same command (maybe with an extra flag?) and wait for the multiple files to be downloaded.

**Comment by ismaell** [comment]
Axel implements `--no-clobber/-c` since version 2.14.

**Comment by AKarbas** [comment]
Oh! So sorry!
Literally didn't see it in man.
