### ISSUE TITLE
How would you download files from a urllist.txt ?

### ISSUE THREAD

**Issue by cocoonkid** [axel-download-accelerator/axel#344]
How would you download files from a urllist.txt ?

**Comment by ismaell** [comment]
If you mean multiple URLs for the same file, you can use: `axel $(cat urllist.txt)`.

However, if you want to download multiple files, you need one axel instance per file; you can do so this way:
`while read url; do axel "$url"; done < urllist.txt`

**Comment by cocoonkid** [comment]
Thanks so much!
