### ISSUE TITLE
URLEncoding issue with UTF8 char

### ISSUE THREAD

**Issue by Sembiance** [axel-download-accelerator/axel#345]
Running v2.17.10 `axel "https://ia800905.us.archive.org/21/items/NetAgustos98/.net Ağustos 1998_thumb.jpg"` fails with:
```
Initializing download: https://ia800905.us.archive.org/21/items/NetAgustos98/.net Ağustos 1998_thumb.jpg
--- Sending request ---
GET /21/items/NetAgustos98/.net%20A%,4%)fustos%201998_thumb.jpg HTTP/1.0
...
--- End of headers ---
(null)
```

That is not the correct encoding for the URL.

It should be (from wget): `GET /21/items/NetAgustos98/.net%20A%C4%9Fustos%201998_thumb.jpg`

**Comment by makunterry** [comment]
Also found this issue, and planned to fix this recently.
