### ISSUE TITLE
REQ: Simple percent output

### ISSUE THREAD

**Issue by xxxserxxx** [axel-download-accelerator/axel#348]
It would be nice to have an option to print progress as a simple percent of total, one number per line. This would facilitate piping progress to other programs and increase user options for using axel.

An example is using axel from within other programs and scripts. Currently, the user has three options: (1) the nice, fancy progress bar; (2) an alternate progress bar; (3) silence. The first two require a terminal and assume control of the progress display; the third provides no status on the download at all. Some example applications:

1. A GUI program could `exec()` axel and read stdout and display progress within the GUI
2. The user could piping the output on the command line to a different progress indicator, e.g., `zenity -- progress --auto-close`.
3. A script could pipe the output to a download status widget in the window manager bar

In my particular case, the web browser [surf](https://surf.suckless.org/) by default manages downloads by forking off a terminal and calling curl. This is easily replaced by axel, but in tiling window managers, futzing with the new terminal so that it doesn't take over focus and. interrupt browsing, or take up too much space, or obscure the browser is troublesome. It would be useful to be able to report on the download either in the bar or in a smaller floating window.

The `-p` (`--percentage`) flag is unused and would be a natural choice.  Output would be a series of simple percentages from 0 to 100 with no other formatting, one per line.

**Comment by luckman212** [comment]
@ismaell Thank you for this. 2 things:

1) the manpage isn't updated, I didn't know this option even existed until I stumbled onto it... 
2) can you post an example syntax of how this can be used e.g. with coreutils `progress`? I tried various things but couldn't get it to work. It just endlessly prints the percentages e.g. screen after screen of fast-scrolling `4...5...6...7...`.

**Comment by ismaell** [comment]
@luckman212 noted.

As for point 2, it's meant to be used with tools that scan for lines a number, like `dialog --gauge`. Example:
```sh
axel -p http://mirror-master.dragonflybsd.org/iso-images/dfly-x86_64-6.2.1_REL.img.bz2 |
    dialog --gauge "Downloading DragonFly BSD" 6 40
```
That will show a progress meter for the  download.

**Comment by xxxserxxx** [comment]
@ismaell it works perfectly, too.  `axel -p ... | zenity --progress --auto-close` is awesome.

**Comment by luckman212** [comment]
@ismaell Thank you for the comments, yes tested with `dialog` and works well! I was trying with `pv` and `progress` etc.

**Comment by luckman212** [comment]
Just want to add, I had problems with `dialog` where it would get stuck sometimes and stop updating. I think maybe it was caused by too much / too fast / repeating output same numbers from axel.

I "solved" it by piping to `awk` first to clean it up and only output the numbers when they actually change...

```shell
axel -p https://downloads.freepbxdistro.org/ISO/SNG7-PBX16-64bit-2202-2.iso |
awk '/^[0-9]+$/ {if($0!=last) print; fflush(); last=$0 }' |
dialog --gauge "Downloading FreePBX" 6 40
```
