### ISSUE TITLE
Plans to support LibreSSL?

### ISSUE THREAD

**Issue by beaglesnuf** [axel-download-accelerator/axel#356]
A lot of null pointer dereference errors, but axel builds and can be used. Here is my log for a dynamic musl 1.2.2 build against LibreSSL 3.3.3: 

https://zerobin.net/?a69e36fec00471e5#N4KPGuXEx7X9QJB0Bc2sOsUb2CxLlzlK6NYVFK+gF7s=

Are there plans to support LibreSSL in a more official capacity? Resultant binary works fine and as expected (so far). Is there a recommended stress tool we can run against axel to ensure error-free operation (particularly with so many null dereferences during compile time)?

**Comment by ismaell** [comment]
Those errors aren't coming from axel's source code... and I have no idea how you get those errors in the linking stage either...

BTW, I regularly test against musl and libressl, it compiles and works fine :wink:.

**Comment by beaglesnuf** [comment]
You are absolutely correct. Problem was libressl was built with -flto. Compiling againsy libressl without -flto and only one error remained:

``  
CC       src/ftp.o
src/ftp.c: In function ‘ftp_wait’:
src/ftp.c:309:8: warning: unused variable ‘s’ [-Wunused-variable]
  309 |  char *s;
      |        ^
CC       src/http.o
``

**Comment by ismaell** [comment]
OK. I'm going to close this then.
