### ISSUE TITLE
Fail to compile with errors

### ISSUE THREAD

**Issue by jenny-cheung** [axel-download-accelerator/axel#358]
Hi developers:
             I met a compile error while compiling the project. Thank you for the help!
The command:
`./configure`

The error:
```
./configure: line 5359: syntax error near unexpected token `git-directory'
./configure: line 5359: `AX_IS_RELEASE(git-directory)'
```

**Comment by ismaell** [comment]
It's explained in the README file. Build from release tarballs if you're just building a release.

**Comment by jenny-cheung** [comment]
OK! Thank you.
