### ISSUE TITLE
Error opening local file in other disk but not in home directory

### ISSUE THREAD

**Issue by aruiplex** [axel-download-accelerator/axel#363]
OS: ubuntu21.10

I can successfully download file in the home directory but cannot in other disk:

In the home download folder:
![image](https://user-images.githubusercontent.com/40193711/140699068-128ad269-3f84-4f58-a1cd-184a4a55fd20.png)

But if I change the output folder into another:

![image](https://user-images.githubusercontent.com/40193711/140699168-84d4053f-8f81-4a98-8af9-ddbb0a13d2c5.png)

The permission is checked.

Thanks!

**Comment by aruiplex** [comment]
Furthermore, if I use `sudo`, the situation is the same

**Comment by Jason23347** [comment]
Maybe this is because your media is readonly.

**Comment by aruiplex** [comment]
> Maybe this is because your media is readonly.

very thanks, but not.

**Comment by ismaell** [comment]
That's odd and unlikely to be a bug in Axel; it's failing to create the main file, not the state file; does `wget` work for you?

It could be a security policy in action, or the filesystem has something special about it. Do you mind to publish the mountpoint information? You can get it with something like:

    awk '$2 ~ /^\/data/' /proc/mounts

And check the logs for AppArmor errors (and anything else you enabled).

**Comment by aruiplex** [comment]
> That's odd and unlikely to be a bug in Axel; it's failing to create the main file, not the state file; does `wget` work for you?
> 
> It could be a security policy in action, or the filesystem has something special about it. Do you mind to publish the mountpoint information? You can get it with something like:
> 
> ```
> awk '$2 ~ /^\/data/' /proc/mounts
> ```
> 
> And check the logs for AppArmor errors (and anything else you enabled).

Sure! The output is like this:
```bash
~$ awk '$2 ~ /^\/data/' /proc/mounts 
/dev/sdc2 /data exfat rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,iocharset=utf8,errors=remount-ro 0 0
```

**Comment by ismaell** [comment]
That's super weird, but then again that's `exfat`... so, does wget work at `/data` or does it fail too?

**Comment by aruiplex** [comment]
> That's super weird, but then again that's `exfat`... so, does wget work at `/data` or does it fail too?

Very thanks your patience. Base on my test, the wget is ok, but the axel is not. The detail is:

```bash
aruix@alinux:/data/temp$ wget https://download.docker.com/linux/centos/docker-ce.repo
--2021-11-13 17:10:24--  https://download.docker.com/linux/centos/docker-ce.repo
Resolving download.docker.com (download.docker.com)... 2600:9000:219a:2600:3:db06:4200:93a1, 2600:9000:219a:d600:3:db06:4200:93a1, 2600:9000:219a:3000:3:db06:4200:93a1, ...
Connecting to download.docker.com (download.docker.com)|2600:9000:219a:2600:3:db06:4200:93a1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1919 (1.9K) [binary/octet-stream]
Saving to: ‘docker-ce.repo’

docker-ce.repo                    100%[=============================================================>]   1.87K  --.-KB/s    in 0s      

2021-11-13 17:10:24 (1.79 GB/s) - ‘docker-ce.repo’ saved [1919/1919]


aruix@alinux:/data/temp$ axel -o docker-ce.repo.axel https://download.docker.com/linux/centos/docker-ce.repo
Initializing download: https://download.docker.com/linux/centos/docker-ce.repo
File size: 1.87402 Kilobyte(s) (1919 bytes)
Opening output file docker-ce.repo.axel
Error opening local file

aruix@alinux:/data/temp$ axel https://download.docker.com/linux/centos/docker-ce.repo
Initializing download: https://download.docker.com/linux/centos/docker-ce.repo
File size: 1.87402 Kilobyte(s) (1919 bytes)
Opening output file docker-ce.repo
Error opening local file

aruix@alinux:/data$ ll
drwxr-xr-x  2 aruix aruix 2097152 11月 13 17:14  temp/
```

**Comment by layarkaca21** [comment]
I got this error too..

[root@vps-726fbd0f ~]# axel -V
Axel 2.17.10 (linux-gnu)

Copyright 2001-2007 Wilmer van der Gaast,
	  2007-2009 Giridhar Appaji Nag,
	  2008-2010 Philipp Hagemeister,
	  2015-2017 Joao Eriberto Mota Filho,
	  2016-2017 Stephen Thirlwall,
	  2017      Ismael Luceno,
	  2017      Antonio Quartulli,
		    and others.
Please, see the CREDITS file.

**Comment by ismaell** [comment]
Looks like a filesystem bug, maybe the `exfat` implementation is faulty.

The only difference I can see is that `wget` ends up calling `open` with `O_TRUNC`, which `axel` doesn't, but I don't see why it would fail on `exfat` without `O_TRUNC`...

**Comment by wlcosta** [comment]
Still unable to use Axel in any other directory beyond home

**Comment by ismaell** [comment]
> Still unable to use Axel in any other directory beyond home. This issue started after I updated my Ubuntu from 18.04 to 20.04

I'm going to need more information than that...

* the error Axel is giving out when failing
* the directory and it's mountpoint information
* a trace if possible (`strace` should be enough).

**Comment by lciti** [comment]
Is it a snap version of axel? If so the error could be due to the snap containment.

**Comment by ismaell** [comment]
I'm going to close this. If some evidence of a bug *in axel* turns up, please reopen.

Note: I can't provide  much support for snap builds, because any issue with that isn't in the axel codebase, so there's nothing I can do about it.
