### ISSUE TITLE
configure: line 7599: syntax error

### ISSUE THREAD

**Issue by samsha1971** [axel-download-accelerator/axel#364]
OS: ubuntu 18.04 ， master version and V2.7.10 has the same error.

$./configure 
...
./configure: line 7599: syntax error near unexpected token `as_ac_var=`$as_echo "ac_cv_func_$ac_func" | $as_tr_sh`'
./configure: line 7599: `  as_ac_var=`$as_echo "ac_cv_func_$ac_func" | $as_tr_sh`

**Comment by ismaell** [comment]
Please specify the origin/version of the source code.

**Comment by samsha1971** [comment]
> Please specify the origin/version of the source code.

from master version

**Comment by samsha1971** [comment]
resolved . delete  three last '\' in configure.ac .

 configure.ac | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/configure.ac b/configure.ac
index a17b0c7..377dba3 100644
--- a/configure.ac
+++ b/configure.ac
@@ -147,14 +147,14 @@ AC_CHECK_FUNCS([ \
 	strrchr \
 	strstr \
 	strtoul \
-	strtoll \
+	strtoll 
 ],, [
     AC_MSG_ERROR([$ac_func is required; it should be part of libc.])
 ])
 
 AC_REPLACE_FUNCS([ \
 	strlcpy \
-	strlcat \
+	strlcat 	
 ])
 
 # Check for missing features/flags
@@ -175,7 +175,7 @@ AS_IF([test "x$with_ssl" != xno], [
     save_LIBS="$LIBS"
     LIBS="$LIBS $SSL_LIBS"
     AC_REPLACE_FUNCS([ \
-        ASN1_STRING_get0_data \
+        ASN1_STRING_get0_data
     ])
     LIBS="$save_LIBS"
 ], AC_MSG_NOTICE([SSL support disabled]))

**Comment by ismaell** [comment]
That might have something to do with the version of autoconf... although it shouldn't matter; it hasn't been a problem with 2.7x at least...
