### ISSUE TITLE
CentOS 8 Package

### ISSUE THREAD

**Issue by Heshmatkhah** [axel-download-accelerator/axel#366]
Hi,
Is there an RPM package for CentOS 8, or Rocky Linux, or Alma Linux?

**Comment by ismaell** [comment]
Currently we don't do builds; if it isn't in the distro repos then no.

There's packages for Fedora, so it should be trivial to make a build for any other RPM-based system.

**Comment by ismaell** [comment]
I keep track of the downstream updates in issues like this: https://github.com/axel-download-accelerator/axel/issues/335
