### ISSUE TITLE
Add a don't-download-again flag

### ISSUE THREAD

**Issue by sdt** [axel-download-accelerator/axel#37]
See #36 

If you ask axel to download a file that already exists, it will add a .0, .1, .2 suffix to the filename until an unused filename is found.

Perhaps a flag to skip already-downloaded files. This would not apply if the state file existed.

**Comment by denji** [comment]
## Branch: no-clobber https://github.com/axel-dl/axel-ideas/tree/no-clobber

Skip files that are already downloaded (don't clobber from `wget`).

* New command-line argument `-c` or `--no-clobber`.
* New config file option `no_clobber = 1`

**Comment by ordex** [comment]
How is the check in wget implemented? Just filename check? or there is also a size check?
Axel could simply check if the .st file exists. If not, it could assume the download is complete and move on (or additionally also check the size).

**Comment by ordex** [comment]
wget manpage talks about filename only. I think we can just mimic the same behaviour then.

**Comment by ordex** [comment]
@ismaell do you agree on using the same command line options as specified by the previous user "-c or --no-clobber" ?

**Comment by denji** [comment]
https://github.com/axel-dl/axel-ideas/compare/fa372d8...d776869

**Comment by ordex** [comment]
@denji glad to see you are still active. I'll comment your code then!

**Comment by ordex** [comment]
@denji actually, could you please make a pull request? there we can comment/review. Thanks!

**Comment by ismaell** [comment]
@ordex I think it's fine to use those options.

**Comment by ordex** [comment]
@ismaell do you think axel should ignore the --no-clobber options if a .st file is found? having a .st file basically means that the previous download has not been completed and axel should continue. However this means trying to be smarter than the user. What should axel do in your opinion? Just stick to the user configured behaviour and skip the file even if the .st one is there?

**Comment by ismaell** [comment]
@ordex just if there's no `.st` file.

Given the way we download files, it only makes sense to always continue a download.
