### ISSUE TITLE
Add early redirect loop detection

### ISSUE THREAD

**Issue by ismaell** [axel-download-accelerator/axel#377]
It might be useful to detect a redirect loop, not just guess based on the number of tries, but actually check the URL, to allow to fail early and a larger default number.

**Comment by Sugarlust** [comment]
Hey, I'm new to opensource and would like to contribute to this. Can you please elaborate on what needs to be done? Thanks.

**Comment by ismaell** [comment]
Hi @Sugarlust, thanks for the interest.

All the code related to connection handling is within `src/conn.c`.

Since HTTP itself is stateless, any repeated request is enough to detect a loop, and since axel isn't very smart, for starters just keeping track of the URLs is enough. An O(N) implementation is fine.

**Comment by Sugarlust** [comment]
Thanks @ismaell I'm gonna look for that and reach you out if I need some help.

**Comment by Sugarlust** [comment]
hey @ismaell I skimmed through the source code and it's pretty confusing for me but I'm surely trying. Can you please tell me how can one keep track of URLs? 
According to my understanding if the same URL repeats then it should be declared redirected right? Then How should I check the URL and what needs to happen next?

**Comment by ismaell** [comment]
If a URL is repeated, then it's a closed loop, and axel can abort early, without reaching `max_redirect`.

Here's the code you need to deal with:
https://github.com/axel-download-accelerator/axel/blob/3af1542e8143d8fa2f50eecf721a9fdbe23ef128/src/conn.c#L401-L435

Everything you need to know is in there.

**Comment by codymichaeljones** [comment]
Hi, @ismaell! Looks like this issue still hasn't been resolved. I'm also new to open source and would like to give it a try.

Since you're okay with an O(n) implementation, could I simply store the URLs in an array and then do a linear scan to check whether the current URL has already been visited?

Is there a naming convention you'd like me to follow when creating a new branch?

**Comment by codymichaeljones** [comment]
Will this do the trick?

https://github.com/codymichaeljones/axel/commit/dfb2f7c11d303f892058c241322240a905e86b42

**Comment by ismaell** [comment]
It's in the right path!

Changes needed:
1. Don't remove the original `max_redirect` check. It needs to be an *additional* restriction, because maybe there's no explicit loop yet but it's still too many redirects, we want to handle both.
2. you can't use `conn->http->headers` to store the URLs (maybe use `malloc(MAX_STRING)` for each, worry not about the memory usage, we can improve that later)
3.  the message should be different, something like "Redirect loop detected"...
4. check your indentation

**Comment by ismaell** [comment]
> Is there a naming convention you'd like me to follow when creating a new branch?

We don't have any, follow your heart. Normally I don't do merge commits, so there's no track of that.

The only hard rule is that your PR must apply cleanly to the development branch, but since it's a slow-moving small project that's easy.

**Comment by ismaell** [comment]
> 2. I'm not sure I fully understand this point. I was using the conn_url() function to get the current URL as a string before I store it inside the urls[] array. How else can I get the current URL? I think I understand your point about malloc'ing enough memory to hold each URL.

Using `conn_url` is correct, but it takes a buffer (1st and 2nd argument) and stores the string there, you need to allocate the buffer, you can't use `conn->http->headers`.

**Comment by codymichaeljones** [comment]
I see. Thanks for clarifying.

`char s[1005];
	char *urls[max_redirect];
    int num_urls = 0;
    char *curr_url;
    long long int i = 0;

	do {
		const char *t;

		conn->supported = true;
		conn->currentbyte = 0;
		pthread_mutex_lock(&conn->lock);
		int setup_ret = conn_setup(conn);
		pthread_mutex_unlock(&conn->lock);
		if (!setup_ret)
			return 0;
		conn_exec(conn);
		conn_disconnect(conn);

		http_filename(conn->http, conn->output_filename);

		/* Code 3xx == redirect */
		if (conn->http->status / 100 != 3)
			break;
		if ((t = http_header(conn->http, "location:")) == NULL)
			return 0;
		sscanf(t, "%1000s", s);
		if (s[0] == '/') {
			abuf_printf(conn->http->headers, "%s%s:%i%s",
				    scheme_from_proto(conn->proto),
				    conn->host, conn->port, s);
			strlcpy(s, conn->http->headers->p, sizeof(s));
		} else if (strstr(s, "://") == NULL) {
			conn_url(conn->http->headers->p,
				 conn->http->headers->len,
				 conn);
			strlcat(conn->http->headers->p, s,
				conn->http->headers->len);
			strlcpy(s, conn->http->headers->p, sizeof(s));
		}

		if (!conn_set(conn, s)) {
			return 0;
		}

		/* check if the download has been redirected to FTP and
		 * report it back to the caller */
		if (PROTO_IS_FTP(conn->proto) && !conn->proxy) {
			return -1;
		}

        if (++i >= conn->conf->max_redirect) {
			fprintf(stderr, _("Too many redirects.\n"));
			return 0;
		}

        /* Check if the current URL has already been visited ... */
        curr_url = malloc(MAX_STRING);
        conn_url(curr_url, MAX_STRING, conn);
        for (int i = 0; i < num_urls; i++) {
		    if (!strcmp(curr_url, urls[i]) {
			    fprintf(stderr, _("Redirect loop detected.\n"));
			    return 0;
		    }
        }

        /* ... if not, store the current URL */
        urls[num_urls] = curr_url;
        num_urls++;
        free(curr_url);
	} while (conn->http->status / 100 == 3);`

This is my attempt to fix everything you mentioned other than the indentation. I don't see where my indentation is wrong. Could you be more specific, please?

**Comment by ismaell** [comment]
I left some comments there. With respect to the indentation, the project uses tabs (8-char wide).

**Comment by codymichaeljones** [comment]
Thanks for all your comments and for walking me through this. I believe the indentation should be fixed now as well as the other issues you commented on in my last commit. How are things looking now?

https://github.com/codymichaeljones/axel/commit/d5c772a9b5e84555308abbd37aa31e3d65f9ea98

Also, is it necessary for me to link to my commits in these comments or is there a better way to demonstrate my progress to you?

**Comment by ismaell** [comment]
It looks good. I will give it a second look in the afternoon. Kudos!

**Comment by codymichaeljones** [comment]
Hi, @ismaell! Should I go ahead and create a PR or wait for you to review my latest commit more carefully?

**Comment by ismaell** [comment]
@codymichaeljones yes, create the PR, please.

**Comment by ismaell** [comment]
Excellent work @codymichaeljones, please check out the changes I made (minor). If you're inclined to do so, it can be further improved. E.g. memory usage could be improved.

Ideas:
* Preallocate a single buffer for all strings to improve memory usage and behaviour.
* Maybe just save hashes of the URLs instead of the strings for huge savings.

**Comment by codymichaeljones** [comment]
Thanks for your patience and for walking me through my first open source contribution. I had fun and would love to keep contributing to this project.

If I were to begin working on the ideas you mentioned, how should I incorporate the changes you've made in the upstream repo in my forked repo? Also, should I continue working in the same branch?

**Comment by ismaell** [comment]
In this specific case, since all your changes were merged but in a modified way, you can just reset (discard changes) your branch to the contents of `master` and continue to work there with: `git reset --hard origin/master`

**Comment by ismaell** [comment]
However, in the case your changes were partially merged, or you have new changes already in your branch, you can do an interactive rebase to edit your branch and continue the work from there with: `git rebase -i origin/master`

**Comment by ismaell** [comment]
Interactive rebase is one of the most useful tools.

**Comment by ismaell** [comment]
Since the basic functionality is merged, I'm going to close this ticket, and the improvements can refer to (the newly created) #392.
