### ISSUE TITLE
interfere with proxychains

### ISSUE THREAD

**Issue by spiderroot2** [axel-download-accelerator/axel#378]
I tried proxychains axel http://example.com but get this error 
ERROR: ld.so: object 'libproxychains.so.3' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
and proxychains not working

**Comment by ismaell** [comment]
That has nothing to do with axel; the error comes from `ld.so`.

**Comment by ismaell** [comment]
You should report the issue to your distribution/OS, it's probably a packaging issue.
