### ISSUE TITLE
[Bug] Why is always ssl error: certificate verify failed

### ISSUE THREAD

**Issue by szh-bash** [axel-download-accelerator/axel#405]
version: 2.17.11
openssl: 3.1.0
-k (--insecure) will work mostly, but why would this error happen? Did i install openssl failed? 
```
➜  local pc axel  https://google.com
[proxychains] DLL init: proxychains-ng 4.16
Initializing download: https://google.com
SSL error: certificate verify failed
(null)
```

**Comment by ismaell** [comment]
Works for me:
```
$ ./axel https://google.com
Initializing download: https://google.com
File size: 18.668 Kilobyte(s) (19116 bytes)
Opening output file default.1
Server unsupported, starting from scratch with one connection.
Starting download

Connection 0 finished

Downloaded 18.668 Kilobyte(s) in 0 second(s). (92.71 KB/s)
```

Perhaps there's an issue but needs more information to reproduce...

**Comment by ismaell** [comment]
@mizzunet This issue is closed. Also, this might be an integration issue. Always fill a bug with Scoop first, they're the ones responsible for end user support, once there's enough information about the problem and provides it isn't an integration issue, then something can be done upstream.
