### ISSUE TITLE
FTP password can include '@' character

### ISSUE THREAD

**Issue by DoubleChuang** [axel-download-accelerator/axel#413]
I can not use the FTP URL such as ftps://username:pass@word@ftp.host.com

**Comment by DoubleChuang** [comment]
https://github.com/axel-download-accelerator/axel/blob/master/src/conn.c#L122

**Comment by Lordakius** [comment]
I would suggest to not enter passwords in this way. See also [this on stackexchange](https://unix.stackexchange.com/questions/78734/why-shouldnt-someone-use-passwords-in-the-command-line).

**Comment by DoubleChuang** [comment]
> I would suggest to not enter passwords in this way. See also [this on stackexchange](https://unix.stackexchange.com/questions/78734/why-shouldnt-someone-use-passwords-in-the-command-line).
> 
> *edit: Regardless, according to [RFC1738](https://www.rfc-editor.org/rfc/rfc1738), more specifically section 5, it is clearly defined that:
> 
> ```
> login          = [ user [ ":" password ] "@" ] hostport
> password       = *[ uchar | ";" | "?" | "&" | "=" ]
> ```
> 
> so I would argue that having an '@'-character in your password does not conform to the RFC

@Lordakius
 
No, I think [RFC1738](https://www.rfc-editor.org/rfc/rfc1738) defined the user and password can use '@' character
because '@' character is number 64 in uchar(0-255) [code](https://onlinegdb.com/HOxe9N9h6)
```
user           = *[ uchar | ";" | "?" | "&" | "=" ]
password       = *[ uchar | ";" | "?" | "&" | "=" ]
```

**Comment by ismaell** [comment]
No, unescaped `@` isn't allowed, since it is `reserved` in  RFC1738:
```
; Miscellaneous definitions
lowalpha       = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" |
                 "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" |
                 "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" |
                 "y" | "z"
hialpha        = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" |
                 "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" |
                 "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
alpha          = lowalpha | hialpha
digit          = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
                 "8" | "9"
safe           = "$" | "-" | "_" | "." | "+"
extra          = "!" | "*" | "'" | "(" | ")" | ","
reserved       = ";" | "/" | "?" | ":" | "@" | "&" | "="
hex            = digit | "A" | "B" | "C" | "D" | "E" | "F" |
                 "a" | "b" | "c" | "d" | "e" | "f"
escape         = "%" hex hex
unreserved     = alpha | digit | safe | extra
uchar          = unreserved | escape
```

On top of that RFC3986 deprecates login information in URLs.
