### ISSUE TITLE
Download doesn't resume 

### ISSUE THREAD

**Issue by rikhtehgaran** [axel-download-accelerator/axel#416]
Hi, I have version 2.17.11 and I downloaded a file from my server after 1% downloaded I stopped it and ran again but it returned File 'something. file' already there; not retrieving.

Also before I use it make .st file but now it doesn't make it anymore

**Comment by ismaell** [comment]
If the .st file is there, then the download is deemed complete. Was the file actually broken/shorter?

**Comment by ismaell** [comment]
Closing since there's no feedback.
