### ISSUE TITLE
Request to add snap as a download option in readme

### ISSUE THREAD

**Issue by soumyaDghosh** [axel-download-accelerator/axel#419]
Hi, the snapcrafters team is maintaining a very stable snap for `axel`. Can you kindly add that as an installation option too? Also, you can have that snap officially as yours!

**Comment by ismaell** [comment]
We don't provide specific instructions for any (pseudo-)OS.

**Comment by ismaell** [comment]
Snapcrafter scan add themselves to the release coordination tickets (https://github.com/axel-download-accelerator/axel/issues/419 currently) to track their progress and get notified on future releases.
