### ISSUE TITLE
2.17.12 build failure

### ISSUE THREAD

**Issue by chenrui333** [axel-download-accelerator/axel#424]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  src/random.c:13:8: error: address argument to atomic operation must be a pointer to _Atomic type ('int *' invalid)
                  if (!atomic_compare_exchange_strong(&fd, &expect, tmp))
                       ^                              ~~~
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/15.0.0/include/stdatomic.h:139:67: note: expanded from macro 'atomic_compare_exchange_strong'
  #define atomic_compare_exchange_strong(object, expected, desired) __c11_atomic_compare_exchange_strong(object, expected, desired, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)
                                                                    ^                                    ~~~~~~
  1 error generated.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/7704615760/job/20997343259?pr=161270
relates to Homebrew/homebrew-core#161270

**Comment by chenrui333** [comment]
@Biswa96 thanks for the pointer, going to try it now.

**Comment by chenrui333** [comment]
yeah, the patch works for me. 👍

**Comment by Biswa96** [comment]
I am not sure if the patch is correct or not. axel maintainer told that the patch is not appropriate https://github.com/termux/termux-packages/issues/19093
