### ISSUE TITLE
HTTPS .mp4 Links

### ISSUE THREAD

**Issue by TheManCashy** [axel-download-accelerator/axel#428]
Hello, so is it possible to use axel to download http links ending in .mp4

https://example.com/videos/video.mp4

I've been trying but it seems to only show like the first 2 minutes the the rest of video is corrupted even though it downloads the full size for says video file i 1.6GB but i can only play 2 minutes of it shows video length 30 minutes but when I try to skip ahead it freezes and just restarts the video.

**Comment by ismaell** [comment]
What are the differences between  the files?
