### ISSUE TITLE
Guidance needed for updating translation-related documents and workflow

### ISSUE THREAD

**Issue by PeterDaveHello** [axel-download-accelerator/axel#436]
Thanks for the awesome open-source project! I'm interested in contributing translations to axel, but I've run into an issue:

The `./autogen.sh` and `./configure` commands mentioned in `po/README-to-translate` seem to be missing in the current project.

It looks like the project's `.gitignore` file might exclude some related files mentioned in the documentation that I couldn't find in the project, such as `/configure` and the `.pot` template file.

I'm not familiar with the project structure here, but maybe it's the reason for the issue mentioned above. Alternatively, there might be a need to provide instructions on generating these files.

**Comment by ismaell** [comment]
I'll update the instructions.

**Comment by ismaell** [comment]
@PeterDaveHello do you think the new instructions are enough?

**Comment by ismaell** [comment]
Reopen if needed.

**Comment by PeterDaveHello** [comment]
Sorry that I didn't have spare time to verify the whole process from scratch, but it did look better now ;) Thanks!
