### ISSUE TITLE
「feature」android

### ISSUE THREAD

**Issue by Fan-Bob** [axel-download-accelerator/axel#438]
Hope add android client

**Comment by ismaell** [comment]
El 12 de abril de 2024 20:20:57 UTC, Fan-Bob ***@***.***> escribió:
>Hope add android client
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/axel-download-accelerator/axel/issues/438
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
Did you try Termux?
