### ISSUE TITLE
Connection gone: SSL through Proxy

### ISSUE THREAD

**Issue by mkdadi** [axel-download-accelerator/axel#45]

**Comment by mkdadi** [comment]
Hi all,
I observed that when using axel with https links through a proxy server, it gives Connection gone error. 

I ran `axel -n 50 https://github.com/mkdadi/ShortTermMC/archive/v3.1.zip` through a http_proxy server.

**Comment by ismaell** [comment]
I accidentally created a duplicate in #111. Closing this one as the other issue contains more information.
