### ISSUE TITLE
Segfault during downloading large file from dropbox

### ISSUE THREAD

**Issue by crimsonvspurple** [axel-download-accelerator/axel#50]
Hello.

I'm getting Segfault when trying to download a 221GB file from dropbox.

wget works fine but axel produces segfault at the start.

axel -n 16 https://www.dropbox.com/[removed]dl=1
Initializing download: https://www.dropbox.com/[removed]dl=1
File size: 238264867109 bytes
Opening output file [removed]
Starting download
Segmentation fault

**Comment by ismaell** [comment]
Could you provide a backtrace or core dump?

**Comment by ordex** [comment]
@crimsonvspurple will to test the latest master and see if the bug is still there? if yes, it would be nice if you could provide a coredump or backtrace, as @ismaell said. Thanks!

**Comment by ordex** [comment]
We haven't been able to replicate this bug yet. @crimsonvspurple if you have a chance, could you test our latest release 2.14.1? Otherwise I'd assume the problem is gone ..

**Comment by ismaell** [comment]
Can't reproduce, I am guessing this is a duplicate of some of the other bug reports. Please re-open if the bug persists.
