### ISSUE TITLE
Many https seg faults

### ISSUE THREAD

**Issue by mcauser** [axel-download-accelerator/axel#54]
Seeing a lot of `Segmentation fault: 11` after upgrading to `2.12` on OSX 10.11.6.
Primarily when downloading 10-20 HTTPS connections.

Tends to happen most when progress is around 95-100% complete.

**Comment by ismaell** [comment]
Can you provide a core file or a backtrace?

**Comment by mcauser** [comment]
What command should I run to get you that?

**Comment by ismaell** [comment]
Backtraces can be obtained using a debugger, e.g. LLDB.

Just prefix the command like this:

	lldb -- command...

Then use the `run` lldb command to launch it, and when it crashes you run `bt all` to generate a backtrace of all threads.

**Comment by ismaell** [comment]
with GDB the procedure is similar:

	gdb --args command...

then `run`, then `thread apply all bt`.

**Comment by nunesapaloma** [comment]
I am facing this same problem specially when I am call the axel via jenkins job. 100% reproducible. I am using this version: 

$ axel --version

Axel version 2.12 (Darwin)

**Comment by ismaell** [comment]
@nunesapaloma Can you provide a backtrace or core dump file?

**Comment by BrainMaestro** [comment]
Hey @ismaell, I have the same issue on macOS. I followed your steps to generate a backtrace with lldb. Let me know if that's what you need. Thanks.

<details>
<summary>Backtrace from `lldb`</summary>
 

> thread` #1: tid = 0x60f3, 0x00007fff8dbb410a libsystem_kernel.dylib`__semwait_signal + 10, queue = 'com.apple.main-thread'
>     frame #0: 0x00007fff8dbb410a libsystem_kernel.dylib`__semwait_signal + 10
>     frame #1: 0x00007fff8db41d0f libsystem_c.dylib`nanosleep + 199
>     frame #2: 0x00007fff8db41c02 libsystem_c.dylib`usleep + 54
>     frame #3: 0x000000010000352e axel`axel_do + 1135
>     frame #4: 0x0000000100007e66 axel`main + 2798
>     frame #5: 0x00007fff8aa475ad libdyld.dylib`start + 1
> 
>   thread #3: tid = 0x6182, 0x00007fff8dbb45e2 libsystem_kernel.dylib`__workq_kernreturn + 10
>     frame #0: 0x00007fff8dbb45e2 libsystem_kernel.dylib`__workq_kernreturn + 10
>     frame #1: 0x00007fff92b22578 libsystem_pthread.dylib`_pthread_wqthread + 1283
>     frame #2: 0x00007fff92b20341 libsystem_pthread.dylib`start_wqthread + 13
> 
>   thread #4: tid = 0x6183, 0x00007fff8dbb4efa libsystem_kernel.dylib`kevent_qos + 10, queue = 'com.apple.libdispatch-manager'
>     frame #0: 0x00007fff8dbb4efa libsystem_kernel.dylib`kevent_qos + 10
>     frame #1: 0x00007fff8b29d165 libdispatch.dylib`_dispatch_mgr_invoke + 216
>     frame #2: 0x00007fff8b29cdcd libdispatch.dylib`_dispatch_mgr_thread + 52
> 
>   thread #5: tid = 0x6184, 0x00007fff8dbb45e2 libsystem_kernel.dylib`__workq_kernreturn + 10
>     frame #0: 0x00007fff8dbb45e2 libsystem_kernel.dylib`__workq_kernreturn + 10
>     frame #1: 0x00007fff92b22578 libsystem_pthread.dylib`_pthread_wqthread + 1283
>     frame #2: 0x00007fff92b20341 libsystem_pthread.dylib`start_wqthread + 13
> 
> * thread #2: tid = 0x61a0, 0x000000010022aefd libssl.1.0.0.dylib`SSL_set_bio + 19, stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
>   * frame #0: 0x000000010022aefd libssl.1.0.0.dylib`SSL_set_bio + 19
>     frame #1: 0x000000010022b048 libssl.1.0.0.dylib`SSL_set_fd + 69
>     frame #2: 0x0000000100006f8a axel`ssl_connect + 47
>     frame #3: 0x00000001000071a8 axel`tcp_connect + 430
>     frame #4: 0x0000000100005f41 axel`http_connect + 226
>     frame #5: 0x0000000100004c76 axel`conn_init + 318
>     frame #6: 0x0000000100004cf7 axel`conn_setup + 65
>     frame #7: 0x000000010000301b axel`setup_thread + 65
>     frame #8: 0x00007fff92b2299d libsystem_pthread.dylib`_pthread_body + 131
>     frame #9: 0x00007fff92b2291a libsystem_pthread.dylib`_pthread_start + 168
>     frame #10: 0x00007fff92b20351 libsystem_pthread.dylib`thread_start + 13
> 
>   thread #6: tid = 0x61a1, 0x00007fff8dbb3532 libsystem_kernel.dylib`__connect + 10
>     frame #0: 0x00007fff8dbb3532 libsystem_kernel.dylib`__connect + 10
>     frame #1: 0x0000000100007178 axel`tcp_connect + 382
>     frame #2: 0x0000000100005f41 axel`http_connect + 226
>     frame #3: 0x0000000100004c76 axel`conn_init + 318
>     frame #4: 0x0000000100004cf7 axel`conn_setup + 65
>     frame #5: 0x000000010000301b axel`setup_thread + 65
>     frame #6: 0x00007fff92b2299d libsystem_pthread.dylib`_pthread_body + 131
>     frame #7: 0x00007fff92b2291a libsystem_pthread.dylib`_pthread_start + 168
>     frame #8: 0x00007fff92b20351 libsystem_pthread.dylib`thread_start + 13
> 
>   thread #7: tid = 0x61a2, 0x00007fff8dbb3532 libsystem_kernel.dylib`__connect + 10
>     frame #0: 0x00007fff8dbb3532 libsystem_kernel.dylib`__connect + 10
>     frame #1: 0x0000000100007178 axel`tcp_connect + 382
>     frame #2: 0x0000000100005f41 axel`http_connect + 226
>     frame #3: 0x0000000100004c76 axel`conn_init + 318
>     frame #4: 0x0000000100004cf7 axel`conn_setup + 65
>     frame #5: 0x000000010000301b axel`setup_thread + 65
>     frame #6: 0x00007fff92b2299d libsystem_pthread.dylib`_pthread_body + 131
>     frame #7: 0x00007fff92b2291a libsystem_pthread.dylib`_pthread_start + 168
>     frame #8: 0x00007fff92b20351 libsystem_pthread.dylib`thread_start + 13
> 
>   thread #8: tid = 0x61a3, 0x000000010022aefd libssl.1.0.0.dylib`SSL_set_bio + 19, stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
>     frame #0: 0x000000010022aefd libssl.1.0.0.dylib`SSL_set_bio + 19
>     frame #1: 0x000000010022b048 libssl.1.0.0.dylib`SSL_set_fd + 69
>     frame #2: 0x0000000100006f8a axel`ssl_connect + 47
>     frame #3: 0x00000001000071a8 axel`tcp_connect + 430
>     frame #4: 0x0000000100005f41 axel`http_connect + 226
>     frame #5: 0x0000000100004c76 axel`conn_init + 318
>     frame #6: 0x0000000100004cf7 axel`conn_setup + 65
>     frame #7: 0x000000010000301b axel`setup_thread + 65
>     frame #8: 0x00007fff92b2299d libsystem_pthread.dylib`_pthread_body + 131
>     frame #9: 0x00007fff92b2291a libsystem_pthread.dylib`_pthread_start + 168
>     frame #10: 0x00007fff92b20351 libsystem_pthread.dylib`thread_start + 13

</details>

**Comment by ismaell** [comment]
@BrainMaestro Excellent. Thanks.

**Comment by ordex** [comment]
For your information, I see this on linux as well. I'll try to grab more info.

**Comment by ordex** [comment]
If anybody is willing to test the fix I pushed in PR #66 .. that would be nice :)

**Comment by ordex** [comment]
Anybody can test 2.14.1 to verify if this issue has been fixed or not? Thanks!

**Comment by mcauser** [comment]
I have yet to see an error on v2.14.1 on OSX 10.12.6
Seems to be fixed. Thanks!

**Comment by ordex** [comment]
Awesome! thanks for your feedback! @ismaell I think we can close this? If any error should re-appear a new ticket can be opened with more details, I think.

**Comment by ismaell** [comment]
@ordex Yes. Closing.
