### ISSUE TITLE
potential data race in getting speed of connections

### ISSUE THREAD

**Issue by viennadd** [axel-download-accelerator/axel#58]
Hi all,

Our bug scanner has reported a data race issue at [text.c#L237](https://github.com/eribertomota/axel/blob/master/src/text.c#L237), 

in function `main`, `search_sortlist` sorts threads created by search_getspeeds,
```c++
j = search_getspeeds( search, i );
search_sortlist( search, i );
```

`search_getspeeds` returns 0 if `pthread_create` failed, 
would it create a part of speedtest threads, then hit one `pthread_create` failure and returns to main function? Could it result a situation that the created threads still running and `search_sortlist` writes to variables used by threads in the same time?

```c++
int search_getspeeds( search_t *results, int count )
{
	.......

	while( done < count )
	{
		for( i = 0; i < count; i ++ )
		{
			if( running < results->conf->search_threads && !results[i].speed )
			{
				results[i].speed = SPEED_ACTIVE;
				results[i].speed_start_time = gettime();
				if( pthread_create( results[i].speed_thread,
					NULL, search_speedtest, &results[i] ) == 0 )
				{
					running ++;
					break;
				}
				else
				{
					return( 0 );        // hit one pthread_create failure here, but some of threads might still running
				}
			}
```

SourceBrella Inc.,
Alex

**Comment by ismaell** [comment]
Good catch.
