### ISSUE TITLE
Close downstream bug reports about HTTP proxy authentication 

### ISSUE THREAD

**Issue by ordex** [axel-download-accelerator/axel#84]
- [x] Bug on Ubuntu: https://bugs.launchpad.net/ubuntu/+source/axel/+bug/922963
- [x] Bug on Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=675964
- [x] Proposed patch: https://lists.alioth.debian.org/pipermail/axel-devel/2011-February/000198.html

**Comment by ordex** [comment]
How about using the encode function provided by OpenSSL? Compiling against OpenSSL is quite standard I think. When that does not happen, we can compile out the http-auth code. What do you think?

**Comment by ismaell** [comment]
We should get those bugs closed then close this one.

**Comment by ordex** [comment]
I am not registered to any of those platform. are you? If not, I will find a way to let them know.

**Comment by ismaell** [comment]
I'll take care of this after the next release.

**Comment by eribertomota** [comment]
Hi,

Let me know if this issue was solved after last release. If yes, my next upload to Debian will be able to close the issue in Ubuntu. To close in Fedora is needed a new upload there to make available the last  Axel version. Axel in Fedora is outdated and you can see it here:

https://repology.org/metapackage/axel/versions

**Comment by ordex** [comment]
I have seen @ismaell has commented on each bug. Have they been closed? or do we need to something else?

**Comment by ismaell** [comment]
@ordex we need to poke the maintainers with a stick until they update the packages :-P, then the bug reports can/will be closed.

**Comment by newedgex** [comment]
Yeah, HTTP authentication is much needed.
Will this be implemented only for the proxy or also for the normal HTTP basic authentication?
Curl has 
` -u, --user <user:password>  Server user and password `

**Comment by ismaell** [comment]
I forgot about this isssue. it's closed.
